// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/Nerzal/gocloak/v13"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepo creates a new instance of MockAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepo {
	mock := &MockAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepo is an autogenerated mock type for the AuthRepo type
type MockAuthRepo struct {
	mock.Mock
}

type MockAuthRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepo) EXPECT() *MockAuthRepo_Expecter {
	return &MockAuthRepo_Expecter{mock: &_m.Mock}
}

// Login provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) Login(ctx context.Context, username string, password string) (*gocloak.JWT, error) {
	ret := _mock.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *gocloak.JWT
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*gocloak.JWT, error)); ok {
		return returnFunc(ctx, username, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *gocloak.JWT); ok {
		r0 = returnFunc(ctx, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gocloak.JWT)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthRepo_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *MockAuthRepo_Expecter) Login(ctx interface{}, username interface{}, password interface{}) *MockAuthRepo_Login_Call {
	return &MockAuthRepo_Login_Call{Call: _e.mock.On("Login", ctx, username, password)}
}

func (_c *MockAuthRepo_Login_Call) Run(run func(ctx context.Context, username string, password string)) *MockAuthRepo_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepo_Login_Call) Return(jWT *gocloak.JWT, err error) *MockAuthRepo_Login_Call {
	_c.Call.Return(jWT, err)
	return _c
}

func (_c *MockAuthRepo_Login_Call) RunAndReturn(run func(ctx context.Context, username string, password string) (*gocloak.JWT, error)) *MockAuthRepo_Login_Call {
	_c.Call.Return(run)
	return _c
}
