// Code generated by MockGen. DO NOT EDIT.
// Source: port.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	vacancy "github.com/HghaVlad/trainee-match/backend/company/internal/domain/vacancy"
	gomock "github.com/golang/mock/gomock"
)

// MockoutboxWriter is a mock of outboxWriter interface.
type MockoutboxWriter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxWriterMockRecorder
}

// MockoutboxWriterMockRecorder is the mock recorder for MockoutboxWriter.
type MockoutboxWriterMockRecorder struct {
	mock *MockoutboxWriter
}

// NewMockoutboxWriter creates a new mock instance.
func NewMockoutboxWriter(ctrl *gomock.Controller) *MockoutboxWriter {
	mock := &MockoutboxWriter{ctrl: ctrl}
	mock.recorder = &MockoutboxWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxWriter) EXPECT() *MockoutboxWriterMockRecorder {
	return m.recorder
}

// WriteVacancyUpdated mocks base method.
func (m *MockoutboxWriter) WriteVacancyUpdated(ctx context.Context, ev vacancy.UpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteVacancyUpdated", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteVacancyUpdated indicates an expected call of WriteVacancyUpdated.
func (mr *MockoutboxWriterMockRecorder) WriteVacancyUpdated(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteVacancyUpdated", reflect.TypeOf((*MockoutboxWriter)(nil).WriteVacancyUpdated), ctx, ev)
}
