// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	company "github.com/HghaVlad/trainee-match/backend/company/internal/domain/company"
	vacancy "github.com/HghaVlad/trainee-match/backend/company/internal/domain/vacancy"
	views "github.com/HghaVlad/trainee-match/backend/company/internal/usecase/vacancy/views"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockVacancyRepo is a mock of VacancyRepo interface.
type MockVacancyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVacancyRepoMockRecorder
}

// MockVacancyRepoMockRecorder is the mock recorder for MockVacancyRepo.
type MockVacancyRepoMockRecorder struct {
	mock *MockVacancyRepo
}

// NewMockVacancyRepo creates a new mock instance.
func NewMockVacancyRepo(ctrl *gomock.Controller) *MockVacancyRepo {
	mock := &MockVacancyRepo{ctrl: ctrl}
	mock.recorder = &MockVacancyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVacancyRepo) EXPECT() *MockVacancyRepoMockRecorder {
	return m.recorder
}

// GetByIDForUpdate mocks base method.
func (m *MockVacancyRepo) GetByIDForUpdate(ctx context.Context, vacancyID, companyID uuid.UUID) (*vacancy.Vacancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForUpdate", ctx, vacancyID, companyID)
	ret0, _ := ret[0].(*vacancy.Vacancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDForUpdate indicates an expected call of GetByIDForUpdate.
func (mr *MockVacancyRepoMockRecorder) GetByIDForUpdate(ctx, vacancyID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForUpdate", reflect.TypeOf((*MockVacancyRepo)(nil).GetByIDForUpdate), ctx, vacancyID, companyID)
}

// Update mocks base method.
func (m *MockVacancyRepo) Update(ctx context.Context, v *vacancy.Vacancy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockVacancyRepoMockRecorder) Update(ctx, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockVacancyRepo)(nil).Update), ctx, v)
}

// MockcompRepo is a mock of compRepo interface.
type MockcompRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcompRepoMockRecorder
}

// MockcompRepoMockRecorder is the mock recorder for MockcompRepo.
type MockcompRepoMockRecorder struct {
	mock *MockcompRepo
}

// NewMockcompRepo creates a new mock instance.
func NewMockcompRepo(ctrl *gomock.Controller) *MockcompRepo {
	mock := &MockcompRepo{ctrl: ctrl}
	mock.recorder = &MockcompRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompRepo) EXPECT() *MockcompRepoMockRecorder {
	return m.recorder
}

// GetByMember mocks base method.
func (m *MockcompRepo) GetByMember(ctx context.Context, compID, userID uuid.UUID) (*company.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMember", ctx, compID, userID)
	ret0, _ := ret[0].(*company.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMember indicates an expected call of GetByMember.
func (mr *MockcompRepoMockRecorder) GetByMember(ctx, compID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMember", reflect.TypeOf((*MockcompRepo)(nil).GetByMember), ctx, compID, userID)
}

// MockCacheRepo is a mock of CacheRepo interface.
type MockCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepoMockRecorder
}

// MockCacheRepoMockRecorder is the mock recorder for MockCacheRepo.
type MockCacheRepoMockRecorder struct {
	mock *MockCacheRepo
}

// NewMockCacheRepo creates a new mock instance.
func NewMockCacheRepo(ctrl *gomock.Controller) *MockCacheRepo {
	mock := &MockCacheRepo{ctrl: ctrl}
	mock.recorder = &MockCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepo) EXPECT() *MockCacheRepoMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockCacheRepo) Del(ctx context.Context, id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", ctx, id)
}

// Del indicates an expected call of Del.
func (mr *MockCacheRepoMockRecorder) Del(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacheRepo)(nil).Del), ctx, id)
}

// MocksearchRepo is a mock of searchRepo interface.
type MocksearchRepo struct {
	ctrl     *gomock.Controller
	recorder *MocksearchRepoMockRecorder
}

// MocksearchRepoMockRecorder is the mock recorder for MocksearchRepo.
type MocksearchRepoMockRecorder struct {
	mock *MocksearchRepo
}

// NewMocksearchRepo creates a new mock instance.
func NewMocksearchRepo(ctrl *gomock.Controller) *MocksearchRepo {
	mock := &MocksearchRepo{ctrl: ctrl}
	mock.recorder = &MocksearchRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksearchRepo) EXPECT() *MocksearchRepoMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MocksearchRepo) Index(ctx context.Context, vac views.VacancySearch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, vac)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MocksearchRepoMockRecorder) Index(ctx, vac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MocksearchRepo)(nil).Index), ctx, vac)
}
