services:
  candidate-db:
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - candidate-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: candidate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d candidate_db" ]
      interval: 20s
      timeout: 5s
      retries: 15
      start_period: 10s

  candidate-service:
    build:
      context: candidate
    environment:
      DB_HOST: candidate-db
      DB_PORT: 5432
      DB_USER: postgres
      DB.PASSWORD: postgres
      DB_NAME: candidate_db
      ADDR: 0.0.0.0:8081
      JWKURL: http://keycloack:8080/realms/trainee-match/protocol/openid-connect/certs

    ports:
      - "8081:8081"


volumes:
  candidate-db-data: