// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepo creates a new instance of MockAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepo {
	mock := &MockAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepo is an autogenerated mock type for the AuthRepo type
type MockAuthRepo struct {
	mock.Mock
}

type MockAuthRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepo) EXPECT() *MockAuthRepo_Expecter {
	return &MockAuthRepo_Expecter{mock: &_m.Mock}
}

// GetUserInfo provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) GetUserInfo(ctx context.Context, token string) (*domain.User, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_GetUserInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserInfo'
type MockAuthRepo_GetUserInfo_Call struct {
	*mock.Call
}

// GetUserInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockAuthRepo_Expecter) GetUserInfo(ctx interface{}, token interface{}) *MockAuthRepo_GetUserInfo_Call {
	return &MockAuthRepo_GetUserInfo_Call{Call: _e.mock.On("GetUserInfo", ctx, token)}
}

func (_c *MockAuthRepo_GetUserInfo_Call) Run(run func(ctx context.Context, token string)) *MockAuthRepo_GetUserInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepo_GetUserInfo_Call) Return(user *domain.User, err error) *MockAuthRepo_GetUserInfo_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepo_GetUserInfo_Call) RunAndReturn(run func(ctx context.Context, token string) (*domain.User, error)) *MockAuthRepo_GetUserInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserRole provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) GetUserRole(ctx context.Context, token string, userID string) (string, error) {
	ret := _mock.Called(ctx, token, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserRole")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, token, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, token, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, token, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_GetUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserRole'
type MockAuthRepo_GetUserRole_Call struct {
	*mock.Call
}

// GetUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - userID string
func (_e *MockAuthRepo_Expecter) GetUserRole(ctx interface{}, token interface{}, userID interface{}) *MockAuthRepo_GetUserRole_Call {
	return &MockAuthRepo_GetUserRole_Call{Call: _e.mock.On("GetUserRole", ctx, token, userID)}
}

func (_c *MockAuthRepo_GetUserRole_Call) Run(run func(ctx context.Context, token string, userID string)) *MockAuthRepo_GetUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepo_GetUserRole_Call) Return(s string, err error) *MockAuthRepo_GetUserRole_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthRepo_GetUserRole_Call) RunAndReturn(run func(ctx context.Context, token string, userID string) (string, error)) *MockAuthRepo_GetUserRole_Call {
	_c.Call.Return(run)
	return _c
}
