// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package getcandidates

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCandidateRepo creates a new instance of MockCandidateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCandidateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCandidateRepo {
	mock := &MockCandidateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCandidateRepo is an autogenerated mock type for the CandidateRepo type
type MockCandidateRepo struct {
	mock.Mock
}

type MockCandidateRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCandidateRepo) EXPECT() *MockCandidateRepo_Expecter {
	return &MockCandidateRepo_Expecter{mock: &_m.Mock}
}

// GetCandidates provides a mock function for the type MockCandidateRepo
func (_mock *MockCandidateRepo) GetCandidates(ctx context.Context, page int, size int) ([]domain.Candidate, error) {
	ret := _mock.Called(ctx, page, size)

	if len(ret) == 0 {
		panic("no return value specified for GetCandidates")
	}

	var r0 []domain.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]domain.Candidate, error)); ok {
		return returnFunc(ctx, page, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []domain.Candidate); ok {
		r0 = returnFunc(ctx, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Candidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, page, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCandidateRepo_GetCandidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCandidates'
type MockCandidateRepo_GetCandidates_Call struct {
	*mock.Call
}

// GetCandidates is a helper method to define mock.On call
//   - ctx context.Context
//   - page int
//   - size int
func (_e *MockCandidateRepo_Expecter) GetCandidates(ctx interface{}, page interface{}, size interface{}) *MockCandidateRepo_GetCandidates_Call {
	return &MockCandidateRepo_GetCandidates_Call{Call: _e.mock.On("GetCandidates", ctx, page, size)}
}

func (_c *MockCandidateRepo_GetCandidates_Call) Run(run func(ctx context.Context, page int, size int)) *MockCandidateRepo_GetCandidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCandidateRepo_GetCandidates_Call) Return(candidates []domain.Candidate, err error) *MockCandidateRepo_GetCandidates_Call {
	_c.Call.Return(candidates, err)
	return _c
}

func (_c *MockCandidateRepo_GetCandidates_Call) RunAndReturn(run func(ctx context.Context, page int, size int) ([]domain.Candidate, error)) *MockCandidateRepo_GetCandidates_Call {
	_c.Call.Return(run)
	return _c
}
