// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCompanyRepo) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCompanyRepoMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCompanyRepo)(nil).Delete), ctx, id)
}

// MockCompMemberRepo is a mock of CompMemberRepo interface.
type MockCompMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompMemberRepoMockRecorder
}

// MockCompMemberRepoMockRecorder is the mock recorder for MockCompMemberRepo.
type MockCompMemberRepoMockRecorder struct {
	mock *MockCompMemberRepo
}

// NewMockCompMemberRepo creates a new mock instance.
func NewMockCompMemberRepo(ctrl *gomock.Controller) *MockCompMemberRepo {
	mock := &MockCompMemberRepo{ctrl: ctrl}
	mock.recorder = &MockCompMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompMemberRepo) EXPECT() *MockCompMemberRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCompMemberRepo) Get(ctx context.Context, userID, companyID uuid.UUID) (*member.CompanyMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, companyID)
	ret0, _ := ret[0].(*member.CompanyMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompMemberRepoMockRecorder) Get(ctx, userID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompMemberRepo)(nil).Get), ctx, userID, companyID)
}

// MockCacheRepo is a mock of CacheRepo interface.
type MockCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepoMockRecorder
}

// MockCacheRepoMockRecorder is the mock recorder for MockCacheRepo.
type MockCacheRepoMockRecorder struct {
	mock *MockCacheRepo
}

// NewMockCacheRepo creates a new mock instance.
func NewMockCacheRepo(ctrl *gomock.Controller) *MockCacheRepo {
	mock := &MockCacheRepo{ctrl: ctrl}
	mock.recorder = &MockCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepo) EXPECT() *MockCacheRepoMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockCacheRepo) Del(ctx context.Context, id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", ctx, id)
}

// Del indicates an expected call of Del.
func (mr *MockCacheRepoMockRecorder) Del(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacheRepo)(nil).Del), ctx, id)
}
