// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package addskill

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillRepo creates a new instance of MockSkillRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillRepo {
	mock := &MockSkillRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillRepo is an autogenerated mock type for the SkillRepo type
type MockSkillRepo struct {
	mock.Mock
}

type MockSkillRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillRepo) EXPECT() *MockSkillRepo_Expecter {
	return &MockSkillRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockSkillRepo
func (_mock *MockSkillRepo) Create(ctx context.Context, skill domain.Skill) (uuid.UUID, error) {
	ret := _mock.Called(ctx, skill)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Skill) (uuid.UUID, error)); ok {
		return returnFunc(ctx, skill)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Skill) uuid.UUID); ok {
		r0 = returnFunc(ctx, skill)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Skill) error); ok {
		r1 = returnFunc(ctx, skill)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockSkillRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - skill domain.Skill
func (_e *MockSkillRepo_Expecter) Create(ctx interface{}, skill interface{}) *MockSkillRepo_Create_Call {
	return &MockSkillRepo_Create_Call{Call: _e.mock.On("Create", ctx, skill)}
}

func (_c *MockSkillRepo_Create_Call) Run(run func(ctx context.Context, skill domain.Skill)) *MockSkillRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Skill
		if args[1] != nil {
			arg1 = args[1].(domain.Skill)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillRepo_Create_Call) Return(uUID uuid.UUID, err error) *MockSkillRepo_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockSkillRepo_Create_Call) RunAndReturn(run func(ctx context.Context, skill domain.Skill) (uuid.UUID, error)) *MockSkillRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}
