// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mocks/port_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	application "github.com/HghaVlad/trainee-match/backend/application/internal/domain/application"
	projection "github.com/HghaVlad/trainee-match/backend/application/internal/domain/projection"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockcandidateProjRepo is a mock of candidateProjRepo interface.
type MockcandidateProjRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcandidateProjRepoMockRecorder
	isgomock struct{}
}

// MockcandidateProjRepoMockRecorder is the mock recorder for MockcandidateProjRepo.
type MockcandidateProjRepoMockRecorder struct {
	mock *MockcandidateProjRepo
}

// NewMockcandidateProjRepo creates a new mock instance.
func NewMockcandidateProjRepo(ctrl *gomock.Controller) *MockcandidateProjRepo {
	mock := &MockcandidateProjRepo{ctrl: ctrl}
	mock.recorder = &MockcandidateProjRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcandidateProjRepo) EXPECT() *MockcandidateProjRepoMockRecorder {
	return m.recorder
}

// GetByUserID mocks base method.
func (m *MockcandidateProjRepo) GetByUserID(ctx context.Context, userID uuid.UUID) (*projection.Candidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*projection.Candidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockcandidateProjRepoMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockcandidateProjRepo)(nil).GetByUserID), ctx, userID)
}

// MockresumeProjRepo is a mock of resumeProjRepo interface.
type MockresumeProjRepo struct {
	ctrl     *gomock.Controller
	recorder *MockresumeProjRepoMockRecorder
	isgomock struct{}
}

// MockresumeProjRepoMockRecorder is the mock recorder for MockresumeProjRepo.
type MockresumeProjRepoMockRecorder struct {
	mock *MockresumeProjRepo
}

// NewMockresumeProjRepo creates a new mock instance.
func NewMockresumeProjRepo(ctrl *gomock.Controller) *MockresumeProjRepo {
	mock := &MockresumeProjRepo{ctrl: ctrl}
	mock.recorder = &MockresumeProjRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockresumeProjRepo) EXPECT() *MockresumeProjRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockresumeProjRepo) GetByID(ctx context.Context, id uuid.UUID) (*projection.Resume, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*projection.Resume)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockresumeProjRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockresumeProjRepo)(nil).GetByID), ctx, id)
}

// MockvacProjRepo is a mock of vacProjRepo interface.
type MockvacProjRepo struct {
	ctrl     *gomock.Controller
	recorder *MockvacProjRepoMockRecorder
	isgomock struct{}
}

// MockvacProjRepoMockRecorder is the mock recorder for MockvacProjRepo.
type MockvacProjRepoMockRecorder struct {
	mock *MockvacProjRepo
}

// NewMockvacProjRepo creates a new mock instance.
func NewMockvacProjRepo(ctrl *gomock.Controller) *MockvacProjRepo {
	mock := &MockvacProjRepo{ctrl: ctrl}
	mock.recorder = &MockvacProjRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvacProjRepo) EXPECT() *MockvacProjRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockvacProjRepo) GetByID(ctx context.Context, vacID uuid.UUID) (*projection.Vacancy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, vacID)
	ret0, _ := ret[0].(*projection.Vacancy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockvacProjRepoMockRecorder) GetByID(ctx, vacID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockvacProjRepo)(nil).GetByID), ctx, vacID)
}

// MockappSnapshotRepo is a mock of appSnapshotRepo interface.
type MockappSnapshotRepo struct {
	ctrl     *gomock.Controller
	recorder *MockappSnapshotRepoMockRecorder
	isgomock struct{}
}

// MockappSnapshotRepoMockRecorder is the mock recorder for MockappSnapshotRepo.
type MockappSnapshotRepoMockRecorder struct {
	mock *MockappSnapshotRepo
}

// NewMockappSnapshotRepo creates a new mock instance.
func NewMockappSnapshotRepo(ctrl *gomock.Controller) *MockappSnapshotRepo {
	mock := &MockappSnapshotRepo{ctrl: ctrl}
	mock.recorder = &MockappSnapshotRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockappSnapshotRepo) EXPECT() *MockappSnapshotRepoMockRecorder {
	return m.recorder
}

// CreateIdempotent mocks base method.
func (m *MockappSnapshotRepo) CreateIdempotent(ctx context.Context, appSnapshot application.Snapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIdempotent", ctx, appSnapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateIdempotent indicates an expected call of CreateIdempotent.
func (mr *MockappSnapshotRepoMockRecorder) CreateIdempotent(ctx, appSnapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIdempotent", reflect.TypeOf((*MockappSnapshotRepo)(nil).CreateIdempotent), ctx, appSnapshot)
}

// MockappRepo is a mock of appRepo interface.
type MockappRepo struct {
	ctrl     *gomock.Controller
	recorder *MockappRepoMockRecorder
	isgomock struct{}
}

// MockappRepoMockRecorder is the mock recorder for MockappRepo.
type MockappRepoMockRecorder struct {
	mock *MockappRepo
}

// NewMockappRepo creates a new mock instance.
func NewMockappRepo(ctrl *gomock.Controller) *MockappRepo {
	mock := &MockappRepo{ctrl: ctrl}
	mock.recorder = &MockappRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockappRepo) EXPECT() *MockappRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockappRepo) Create(ctx context.Context, app application.Application) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, app)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockappRepoMockRecorder) Create(ctx, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockappRepo)(nil).Create), ctx, app)
}

// MockappHistoryRepo is a mock of appHistoryRepo interface.
type MockappHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockappHistoryRepoMockRecorder
	isgomock struct{}
}

// MockappHistoryRepoMockRecorder is the mock recorder for MockappHistoryRepo.
type MockappHistoryRepoMockRecorder struct {
	mock *MockappHistoryRepo
}

// NewMockappHistoryRepo creates a new mock instance.
func NewMockappHistoryRepo(ctrl *gomock.Controller) *MockappHistoryRepo {
	mock := &MockappHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockappHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockappHistoryRepo) EXPECT() *MockappHistoryRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockappHistoryRepo) Add(ctx context.Context, change application.StatusChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, change)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockappHistoryRepoMockRecorder) Add(ctx, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockappHistoryRepo)(nil).Add), ctx, change)
}
