// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockCompanyMemberRepo is a mock of CompanyMemberRepo interface.
type MockCompanyMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyMemberRepoMockRecorder
}

// MockCompanyMemberRepoMockRecorder is the mock recorder for MockCompanyMemberRepo.
type MockCompanyMemberRepoMockRecorder struct {
	mock *MockCompanyMemberRepo
}

// NewMockCompanyMemberRepo creates a new mock instance.
func NewMockCompanyMemberRepo(ctrl *gomock.Controller) *MockCompanyMemberRepo {
	mock := &MockCompanyMemberRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyMemberRepo) EXPECT() *MockCompanyMemberRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCompanyMemberRepo) Delete(ctx context.Context, userID, companyID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, userID, companyID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCompanyMemberRepoMockRecorder) Delete(ctx, userID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCompanyMemberRepo)(nil).Delete), ctx, userID, companyID)
}

// Get mocks base method.
func (m *MockCompanyMemberRepo) Get(ctx context.Context, userID, companyID uuid.UUID) (*member.CompanyMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, companyID)
	ret0, _ := ret[0].(*member.CompanyMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompanyMemberRepoMockRecorder) Get(ctx, userID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompanyMemberRepo)(nil).Get), ctx, userID, companyID)
}

// GetCompanyRoleCount mocks base method.
func (m *MockCompanyMemberRepo) GetCompanyRoleCount(ctx context.Context, companyID uuid.UUID, role member.CompanyRole) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCompanyRoleCount", ctx, companyID, role)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCompanyRoleCount indicates an expected call of GetCompanyRoleCount.
func (mr *MockCompanyMemberRepoMockRecorder) GetCompanyRoleCount(ctx, companyID, role interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCompanyRoleCount", reflect.TypeOf((*MockCompanyMemberRepo)(nil).GetCompanyRoleCount), ctx, companyID, role)
}
