// Code generated by MockGen. DO NOT EDIT.
// Source: port.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	gomock "github.com/golang/mock/gomock"
)

// MockoutboxWriter is a mock of outboxWriter interface.
type MockoutboxWriter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxWriterMockRecorder
}

// MockoutboxWriterMockRecorder is the mock recorder for MockoutboxWriter.
type MockoutboxWriterMockRecorder struct {
	mock *MockoutboxWriter
}

// NewMockoutboxWriter creates a new mock instance.
func NewMockoutboxWriter(ctrl *gomock.Controller) *MockoutboxWriter {
	mock := &MockoutboxWriter{ctrl: ctrl}
	mock.recorder = &MockoutboxWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxWriter) EXPECT() *MockoutboxWriterMockRecorder {
	return m.recorder
}

// WriteCompanyMemberAdded mocks base method.
func (m *MockoutboxWriter) WriteCompanyMemberAdded(ctx context.Context, ev member.AddedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCompanyMemberAdded", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCompanyMemberAdded indicates an expected call of WriteCompanyMemberAdded.
func (mr *MockoutboxWriterMockRecorder) WriteCompanyMemberAdded(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCompanyMemberAdded", reflect.TypeOf((*MockoutboxWriter)(nil).WriteCompanyMemberAdded), ctx, ev)
}
