// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	userhr "github.com/HghaVlad/trainee-match/backend/company/internal/usecase/projection/userhr"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockcompanyMemberRepo is a mock of companyMemberRepo interface.
type MockcompanyMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcompanyMemberRepoMockRecorder
}

// MockcompanyMemberRepoMockRecorder is the mock recorder for MockcompanyMemberRepo.
type MockcompanyMemberRepoMockRecorder struct {
	mock *MockcompanyMemberRepo
}

// NewMockcompanyMemberRepo creates a new mock instance.
func NewMockcompanyMemberRepo(ctrl *gomock.Controller) *MockcompanyMemberRepo {
	mock := &MockcompanyMemberRepo{ctrl: ctrl}
	mock.recorder = &MockcompanyMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompanyMemberRepo) EXPECT() *MockcompanyMemberRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockcompanyMemberRepo) Create(ctx context.Context, member *member.CompanyMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockcompanyMemberRepoMockRecorder) Create(ctx, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockcompanyMemberRepo)(nil).Create), ctx, member)
}

// Get mocks base method.
func (m *MockcompanyMemberRepo) Get(ctx context.Context, userID, companyID uuid.UUID) (*member.CompanyMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, companyID)
	ret0, _ := ret[0].(*member.CompanyMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockcompanyMemberRepoMockRecorder) Get(ctx, userID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockcompanyMemberRepo)(nil).Get), ctx, userID, companyID)
}

// MockhrProjRepo is a mock of hrProjRepo interface.
type MockhrProjRepo struct {
	ctrl     *gomock.Controller
	recorder *MockhrProjRepoMockRecorder
}

// MockhrProjRepoMockRecorder is the mock recorder for MockhrProjRepo.
type MockhrProjRepoMockRecorder struct {
	mock *MockhrProjRepo
}

// NewMockhrProjRepo creates a new mock instance.
func NewMockhrProjRepo(ctrl *gomock.Controller) *MockhrProjRepo {
	mock := &MockhrProjRepo{ctrl: ctrl}
	mock.recorder = &MockhrProjRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockhrProjRepo) EXPECT() *MockhrProjRepoMockRecorder {
	return m.recorder
}

// GetByUsername mocks base method.
func (m *MockhrProjRepo) GetByUsername(ctx context.Context, username string) (*userhr.Projection, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUsername", ctx, username)
	ret0, _ := ret[0].(*userhr.Projection)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUsername indicates an expected call of GetByUsername.
func (mr *MockhrProjRepoMockRecorder) GetByUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUsername", reflect.TypeOf((*MockhrProjRepo)(nil).GetByUsername), ctx, username)
}
