// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockCompanyMemberRepo is a mock of CompanyMemberRepo interface.
type MockCompanyMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyMemberRepoMockRecorder
}

// MockCompanyMemberRepoMockRecorder is the mock recorder for MockCompanyMemberRepo.
type MockCompanyMemberRepoMockRecorder struct {
	mock *MockCompanyMemberRepo
}

// NewMockCompanyMemberRepo creates a new mock instance.
func NewMockCompanyMemberRepo(ctrl *gomock.Controller) *MockCompanyMemberRepo {
	mock := &MockCompanyMemberRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyMemberRepo) EXPECT() *MockCompanyMemberRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCompanyMemberRepo) Create(ctx context.Context, member *member.CompanyMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCompanyMemberRepoMockRecorder) Create(ctx, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompanyMemberRepo)(nil).Create), ctx, member)
}

// Get mocks base method.
func (m *MockCompanyMemberRepo) Get(ctx context.Context, userID, companyID uuid.UUID) (*member.CompanyMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, companyID)
	ret0, _ := ret[0].(*member.CompanyMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompanyMemberRepoMockRecorder) Get(ctx, userID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompanyMemberRepo)(nil).Get), ctx, userID, companyID)
}
