// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// CandidateRepo is an autogenerated mock type for the CandidateRepo type
type CandidateRepo struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *CandidateRepo) GetByID(ctx context.Context, id uuid.UUID) (domain.Candidate, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Candidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Candidate, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Candidate); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPhone provides a mock function with given fields: ctx, phone
func (_m *CandidateRepo) GetByPhone(ctx context.Context, phone string) (domain.Candidate, error) {
	ret := _m.Called(ctx, phone)

	if len(ret) == 0 {
		panic("no return value specified for GetByPhone")
	}

	var r0 domain.Candidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Candidate, error)); ok {
		return rf(ctx, phone)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Candidate); ok {
		r0 = rf(ctx, phone)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, phone)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByTelegram provides a mock function with given fields: ctx, telegram
func (_m *CandidateRepo) GetByTelegram(ctx context.Context, telegram string) (domain.Candidate, error) {
	ret := _m.Called(ctx, telegram)

	if len(ret) == 0 {
		panic("no return value specified for GetByTelegram")
	}

	var r0 domain.Candidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Candidate, error)); ok {
		return rf(ctx, telegram)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Candidate); ok {
		r0 = rf(ctx, telegram)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, telegram)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, candidate
func (_m *CandidateRepo) Update(ctx context.Context, candidate domain.Candidate) (domain.Candidate, error) {
	ret := _m.Called(ctx, candidate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Candidate
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Candidate) (domain.Candidate, error)); ok {
		return rf(ctx, candidate)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Candidate) domain.Candidate); ok {
		r0 = rf(ctx, candidate)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Candidate) error); ok {
		r1 = rf(ctx, candidate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCandidateRepo creates a new instance of CandidateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCandidateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CandidateRepo {
	mock := &CandidateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
