// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: candidate/v1/candidate.proto

package candidatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetCandidateByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateByUserIdRequest) Reset() {
	*x = GetCandidateByUserIdRequest{}
	mi := &file_candidate_v1_candidate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateByUserIdRequest) ProtoMessage() {}

func (x *GetCandidateByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candidate_v1_candidate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetCandidateByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_candidate_v1_candidate_proto_rawDescGZIP(), []int{0}
}

func (x *GetCandidateByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetResumeByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResumeId      string                 `protobuf:"bytes,1,opt,name=resume_id,json=resumeId,proto3" json:"resume_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeByIdRequest) Reset() {
	*x = GetResumeByIdRequest{}
	mi := &file_candidate_v1_candidate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeByIdRequest) ProtoMessage() {}

func (x *GetResumeByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_candidate_v1_candidate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeByIdRequest.ProtoReflect.Descriptor instead.
func (*GetResumeByIdRequest) Descriptor() ([]byte, []int) {
	return file_candidate_v1_candidate_proto_rawDescGZIP(), []int{1}
}

func (x *GetResumeByIdRequest) GetResumeId() string {
	if x != nil {
		return x.ResumeId
	}
	return ""
}

func (x *GetResumeByIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetCandidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Telegram      string                 `protobuf:"bytes,4,opt,name=telegram,proto3" json:"telegram,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Birthday      string                 `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCandidateResponse) Reset() {
	*x = GetCandidateResponse{}
	mi := &file_candidate_v1_candidate_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCandidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCandidateResponse) ProtoMessage() {}

func (x *GetCandidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_candidate_v1_candidate_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCandidateResponse.ProtoReflect.Descriptor instead.
func (*GetCandidateResponse) Descriptor() ([]byte, []int) {
	return file_candidate_v1_candidate_proto_rawDescGZIP(), []int{2}
}

func (x *GetCandidateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetCandidateResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetCandidateResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetCandidateResponse) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

func (x *GetCandidateResponse) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetCandidateResponse) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

type GetResumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResumeResponse) Reset() {
	*x = GetResumeResponse{}
	mi := &file_candidate_v1_candidate_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResumeResponse) ProtoMessage() {}

func (x *GetResumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_candidate_v1_candidate_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResumeResponse.ProtoReflect.Descriptor instead.
func (*GetResumeResponse) Descriptor() ([]byte, []int) {
	return file_candidate_v1_candidate_proto_rawDescGZIP(), []int{3}
}

func (x *GetResumeResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetResumeResponse) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *GetResumeResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetResumeResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_candidate_v1_candidate_proto protoreflect.FileDescriptor

const file_candidate_v1_candidate_proto_rawDesc = "" +
	"\n" +
	"\x1ccandidate/v1/candidate.proto\x12\fcandidate.v1\"6\n" +
	"\x1bGetCandidateByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"L\n" +
	"\x14GetResumeByIdRequest\x12\x1b\n" +
	"\tresume_id\x18\x01 \x01(\tR\bresumeId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"\xa1\x01\n" +
	"\x14GetCandidateResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x1a\n" +
	"\btelegram\x18\x04 \x01(\tR\btelegram\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x1a\n" +
	"\bbirthday\x18\x06 \x01(\tR\bbirthday\"r\n" +
	"\x11GetResumeResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcandidate_id\x18\x02 \x01(\tR\vcandidateId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status2\xc7\x01\n" +
	"\x10CandidateService\x12]\n" +
	"\fGetCandidate\x12).candidate.v1.GetCandidateByUserIdRequest\x1a\".candidate.v1.GetCandidateResponse\x12T\n" +
	"\rGetResumeById\x12\".candidate.v1.GetResumeByIdRequest\x1a\x1f.candidate.v1.GetResumeResponseBQZOgithub.com/HghaVlad/trainee-match/backend/contracts/go/candidate/v1;candidatev1b\x06proto3"

var (
	file_candidate_v1_candidate_proto_rawDescOnce sync.Once
	file_candidate_v1_candidate_proto_rawDescData []byte
)

func file_candidate_v1_candidate_proto_rawDescGZIP() []byte {
	file_candidate_v1_candidate_proto_rawDescOnce.Do(func() {
		file_candidate_v1_candidate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_candidate_v1_candidate_proto_rawDesc), len(file_candidate_v1_candidate_proto_rawDesc)))
	})
	return file_candidate_v1_candidate_proto_rawDescData
}

var file_candidate_v1_candidate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_candidate_v1_candidate_proto_goTypes = []any{
	(*GetCandidateByUserIdRequest)(nil), // 0: candidate.v1.GetCandidateByUserIdRequest
	(*GetResumeByIdRequest)(nil),        // 1: candidate.v1.GetResumeByIdRequest
	(*GetCandidateResponse)(nil),        // 2: candidate.v1.GetCandidateResponse
	(*GetResumeResponse)(nil),           // 3: candidate.v1.GetResumeResponse
}
var file_candidate_v1_candidate_proto_depIdxs = []int32{
	0, // 0: candidate.v1.CandidateService.GetCandidate:input_type -> candidate.v1.GetCandidateByUserIdRequest
	1, // 1: candidate.v1.CandidateService.GetResumeById:input_type -> candidate.v1.GetResumeByIdRequest
	2, // 2: candidate.v1.CandidateService.GetCandidate:output_type -> candidate.v1.GetCandidateResponse
	3, // 3: candidate.v1.CandidateService.GetResumeById:output_type -> candidate.v1.GetResumeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_candidate_v1_candidate_proto_init() }
func file_candidate_v1_candidate_proto_init() {
	if File_candidate_v1_candidate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_candidate_v1_candidate_proto_rawDesc), len(file_candidate_v1_candidate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_candidate_v1_candidate_proto_goTypes,
		DependencyIndexes: file_candidate_v1_candidate_proto_depIdxs,
		MessageInfos:      file_candidate_v1_candidate_proto_msgTypes,
	}.Build()
	File_candidate_v1_candidate_proto = out.File
	file_candidate_v1_candidate_proto_goTypes = nil
	file_candidate_v1_candidate_proto_depIdxs = nil
}
