// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: candidate/v1/candidate.proto

package candidatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CandidateService_GetCandidate_FullMethodName  = "/candidate.v1.CandidateService/GetCandidate"
	CandidateService_GetResumeById_FullMethodName = "/candidate.v1.CandidateService/GetResumeById"
)

// CandidateServiceClient is the client API for CandidateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CandidateServiceClient interface {
	GetCandidate(ctx context.Context, in *GetCandidateByUserIdRequest, opts ...grpc.CallOption) (*GetCandidateResponse, error)
	GetResumeById(ctx context.Context, in *GetResumeByIdRequest, opts ...grpc.CallOption) (*GetResumeResponse, error)
}

type candidateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCandidateServiceClient(cc grpc.ClientConnInterface) CandidateServiceClient {
	return &candidateServiceClient{cc}
}

func (c *candidateServiceClient) GetCandidate(ctx context.Context, in *GetCandidateByUserIdRequest, opts ...grpc.CallOption) (*GetCandidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCandidateResponse)
	err := c.cc.Invoke(ctx, CandidateService_GetCandidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *candidateServiceClient) GetResumeById(ctx context.Context, in *GetResumeByIdRequest, opts ...grpc.CallOption) (*GetResumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResumeResponse)
	err := c.cc.Invoke(ctx, CandidateService_GetResumeById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CandidateServiceServer is the server API for CandidateService service.
// All implementations must embed UnimplementedCandidateServiceServer
// for forward compatibility.
type CandidateServiceServer interface {
	GetCandidate(context.Context, *GetCandidateByUserIdRequest) (*GetCandidateResponse, error)
	GetResumeById(context.Context, *GetResumeByIdRequest) (*GetResumeResponse, error)
	mustEmbedUnimplementedCandidateServiceServer()
}

// UnimplementedCandidateServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCandidateServiceServer struct{}

func (UnimplementedCandidateServiceServer) GetCandidate(context.Context, *GetCandidateByUserIdRequest) (*GetCandidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCandidate not implemented")
}
func (UnimplementedCandidateServiceServer) GetResumeById(context.Context, *GetResumeByIdRequest) (*GetResumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResumeById not implemented")
}
func (UnimplementedCandidateServiceServer) mustEmbedUnimplementedCandidateServiceServer() {}
func (UnimplementedCandidateServiceServer) testEmbeddedByValue()                          {}

// UnsafeCandidateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CandidateServiceServer will
// result in compilation errors.
type UnsafeCandidateServiceServer interface {
	mustEmbedUnimplementedCandidateServiceServer()
}

func RegisterCandidateServiceServer(s grpc.ServiceRegistrar, srv CandidateServiceServer) {
	// If the following call panics, it indicates UnimplementedCandidateServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CandidateService_ServiceDesc, srv)
}

func _CandidateService_GetCandidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCandidateByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).GetCandidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateService_GetCandidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).GetCandidate(ctx, req.(*GetCandidateByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CandidateService_GetResumeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResumeByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CandidateServiceServer).GetResumeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CandidateService_GetResumeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CandidateServiceServer).GetResumeById(ctx, req.(*GetResumeByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CandidateService_ServiceDesc is the grpc.ServiceDesc for CandidateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CandidateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "candidate.v1.CandidateService",
	HandlerType: (*CandidateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCandidate",
			Handler:    _CandidateService_GetCandidate_Handler,
		},
		{
			MethodName: "GetResumeById",
			Handler:    _CandidateService_GetResumeById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "candidate/v1/candidate.proto",
}
