{
  "type": "record",
  "name": "ResumeUpdated",
  "namespace": "traineematch.resume",
  "fields": [
    {
      "name": "event_id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "resume_id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "occurred_at",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "id",
      "type": "string"
    },
    {
      "name": "candidate_id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "name",
      "type": "string"
    },
    {
      "name": "data",
      "type": "traineematch.resume.ResumeData"
    },
    {
      "name": "status",
      "type": "traineematch.resume.ResumeStatus"
    },
    {
      "name": "created_at",
      "type": [
        "null",
        {
          "type": "long",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    },
    {
      "name": "updated_at",
      "type": [
        "null",
        {
          "type": "long",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    }
  ]
}

{
  "type": "record",
  "namespace": "traineematch.resume",
  "name": "ResumeData",
  "fields": [
    {
      "name": "last_name",
      "type": "string"
    },
    {
      "name": "first_name",
      "type": "string"
    },
    {
      "name": "middle_name",
      "type": "string"
    },
    {
      "name": "date_of_birth",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "email",
      "type": "string"
    },
    {
      "name": "phone",
      "type": "string"
    },
    {
      "name": "city",
      "type": "string"
    },
    {
      "name": "citizenship",
      "type": "string"
    },
    {
      "name": "education",
      "type": {
        "type": "array",
        "items": "traineematch.resume.Education"
      }
    },
    {
      "name": "work_experiences",
      "type": {
        "type": "array",
        "items": "traineematch.resume.WorkExperience"
      }
    },
    {
      "name": "skills_list",
      "type": {
        "type": "array",
        "items": "string"
      }
    },
    {
      "name": "additional_info",
      "type": "string"
    },
    {
      "name": "portfolio_link",
      "type": "string"
    },
    {
      "name": "desired_format",
      "type": "string"
    },
    {
      "name": "english_level",
      "type": "string"
    }
  ]
}

{
  "type": "record",
  "namespace": "traineematch.resume",
  "name": "Education",
  "fields": [
    {
      "name": "level",
      "type": "string"
    },
    {
      "name": "university",
      "type": "string"
    },
    {
      "name": "faculty",
      "type": "string"
    },
    {
      "name": "specialization",
      "type": "string"
    },
    {
      "name": "start_year",
      "type": "int"
    },
    {
      "name": "end_year",
      "type": "int"
    },
    {
      "name": "format",
      "type": "string"
    }
  ]
}

{
  "type": "record",
  "namespace": "traineematch.resume",
  "name": "WorkExperience",
  "fields": [
    {
      "name": "position",
      "type": "string"
    },
    {
      "name": "company",
      "type": "string"
    },
    {
      "name": "period",
      "type": "string"
    },
    {
      "name": "responsibilities",
      "type": "string"
    }
  ]
}

{
  "type": "enum",
  "namespace": "traineematch.resume",
  "name": "ResumeStatus",
  "symbols": [
    "draft",
    "published"
  ]
}