// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/port_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	vacancy "github.com/HghaVlad/trainee-match/backend/company/internal/domain/vacancy"
	moderationstatus "github.com/HghaVlad/trainee-match/backend/company/internal/usecase/vacancy/moderationstatus"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockvacancyRepo is a mock of vacancyRepo interface.
type MockvacancyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockvacancyRepoMockRecorder
	isgomock struct{}
}

// MockvacancyRepoMockRecorder is the mock recorder for MockvacancyRepo.
type MockvacancyRepoMockRecorder struct {
	mock *MockvacancyRepo
}

// NewMockvacancyRepo creates a new mock instance.
func NewMockvacancyRepo(ctrl *gomock.Controller) *MockvacancyRepo {
	mock := &MockvacancyRepo{ctrl: ctrl}
	mock.recorder = &MockvacancyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockvacancyRepo) EXPECT() *MockvacancyRepoMockRecorder {
	return m.recorder
}

// UpdateModerationStatus mocks base method.
func (m *MockvacancyRepo) UpdateModerationStatus(ctx context.Context, vacancyID uuid.UUID, status vacancy.ModerationStatus, when time.Time) (*moderationstatus.UpdateModerationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModerationStatus", ctx, vacancyID, status, when)
	ret0, _ := ret[0].(*moderationstatus.UpdateModerationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModerationStatus indicates an expected call of UpdateModerationStatus.
func (mr *MockvacancyRepoMockRecorder) UpdateModerationStatus(ctx, vacancyID, status, when any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModerationStatus", reflect.TypeOf((*MockvacancyRepo)(nil).UpdateModerationStatus), ctx, vacancyID, status, when)
}

// MockcompanyRepo is a mock of companyRepo interface.
type MockcompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcompanyRepoMockRecorder
	isgomock struct{}
}

// MockcompanyRepoMockRecorder is the mock recorder for MockcompanyRepo.
type MockcompanyRepoMockRecorder struct {
	mock *MockcompanyRepo
}

// NewMockcompanyRepo creates a new mock instance.
func NewMockcompanyRepo(ctrl *gomock.Controller) *MockcompanyRepo {
	mock := &MockcompanyRepo{ctrl: ctrl}
	mock.recorder = &MockcompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompanyRepo) EXPECT() *MockcompanyRepoMockRecorder {
	return m.recorder
}

// DecrementOpenVacancies mocks base method.
func (m *MockcompanyRepo) DecrementOpenVacancies(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementOpenVacancies", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementOpenVacancies indicates an expected call of DecrementOpenVacancies.
func (mr *MockcompanyRepoMockRecorder) DecrementOpenVacancies(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementOpenVacancies", reflect.TypeOf((*MockcompanyRepo)(nil).DecrementOpenVacancies), ctx, id)
}

// IncrementOpenVacancies mocks base method.
func (m *MockcompanyRepo) IncrementOpenVacancies(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOpenVacancies", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOpenVacancies indicates an expected call of IncrementOpenVacancies.
func (mr *MockcompanyRepoMockRecorder) IncrementOpenVacancies(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOpenVacancies", reflect.TypeOf((*MockcompanyRepo)(nil).IncrementOpenVacancies), ctx, id)
}

// MockoutboxWriter is a mock of outboxWriter interface.
type MockoutboxWriter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxWriterMockRecorder
	isgomock struct{}
}

// MockoutboxWriterMockRecorder is the mock recorder for MockoutboxWriter.
type MockoutboxWriterMockRecorder struct {
	mock *MockoutboxWriter
}

// NewMockoutboxWriter creates a new mock instance.
func NewMockoutboxWriter(ctrl *gomock.Controller) *MockoutboxWriter {
	mock := &MockoutboxWriter{ctrl: ctrl}
	mock.recorder = &MockoutboxWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxWriter) EXPECT() *MockoutboxWriterMockRecorder {
	return m.recorder
}

// WriteVacancyModerationUpdated mocks base method.
func (m *MockoutboxWriter) WriteVacancyModerationUpdated(ctx context.Context, ev vacancy.ModerationUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteVacancyModerationUpdated", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteVacancyModerationUpdated indicates an expected call of WriteVacancyModerationUpdated.
func (mr *MockoutboxWriterMockRecorder) WriteVacancyModerationUpdated(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteVacancyModerationUpdated", reflect.TypeOf((*MockoutboxWriter)(nil).WriteVacancyModerationUpdated), ctx, ev)
}

// MockcacheRepo is a mock of cacheRepo interface.
type MockcacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcacheRepoMockRecorder
	isgomock struct{}
}

// MockcacheRepoMockRecorder is the mock recorder for MockcacheRepo.
type MockcacheRepoMockRecorder struct {
	mock *MockcacheRepo
}

// NewMockcacheRepo creates a new mock instance.
func NewMockcacheRepo(ctrl *gomock.Controller) *MockcacheRepo {
	mock := &MockcacheRepo{ctrl: ctrl}
	mock.recorder = &MockcacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcacheRepo) EXPECT() *MockcacheRepoMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockcacheRepo) Del(ctx context.Context, id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", ctx, id)
}

// Del indicates an expected call of Del.
func (mr *MockcacheRepoMockRecorder) Del(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockcacheRepo)(nil).Del), ctx, id)
}
