// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	publish "github.com/HghaVlad/trainee-match/backend/company/internal/usecase/vacancy/publish"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockVacancyRepo is a mock of VacancyRepo interface.
type MockVacancyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVacancyRepoMockRecorder
}

// MockVacancyRepoMockRecorder is the mock recorder for MockVacancyRepo.
type MockVacancyRepoMockRecorder struct {
	mock *MockVacancyRepo
}

// NewMockVacancyRepo creates a new mock instance.
func NewMockVacancyRepo(ctrl *gomock.Controller) *MockVacancyRepo {
	mock := &MockVacancyRepo{ctrl: ctrl}
	mock.recorder = &MockVacancyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVacancyRepo) EXPECT() *MockVacancyRepoMockRecorder {
	return m.recorder
}

// GetPublishedEventView mocks base method.
func (m *MockVacancyRepo) GetPublishedEventView(ctx context.Context, vacancyID, companyID uuid.UUID) (*publish.PublishedEventView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublishedEventView", ctx, vacancyID, companyID)
	ret0, _ := ret[0].(*publish.PublishedEventView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublishedEventView indicates an expected call of GetPublishedEventView.
func (mr *MockVacancyRepoMockRecorder) GetPublishedEventView(ctx, vacancyID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublishedEventView", reflect.TypeOf((*MockVacancyRepo)(nil).GetPublishedEventView), ctx, vacancyID, companyID)
}

// Publish mocks base method.
func (m *MockVacancyRepo) Publish(ctx context.Context, vacID, compID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, vacID, compID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockVacancyRepoMockRecorder) Publish(ctx, vacID, compID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockVacancyRepo)(nil).Publish), ctx, vacID, compID)
}

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// IncrementOpenVacancies mocks base method.
func (m *MockCompanyRepo) IncrementOpenVacancies(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementOpenVacancies", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementOpenVacancies indicates an expected call of IncrementOpenVacancies.
func (mr *MockCompanyRepoMockRecorder) IncrementOpenVacancies(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementOpenVacancies", reflect.TypeOf((*MockCompanyRepo)(nil).IncrementOpenVacancies), ctx, id)
}

// MockCacheRepo is a mock of CacheRepo interface.
type MockCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepoMockRecorder
}

// MockCacheRepoMockRecorder is the mock recorder for MockCacheRepo.
type MockCacheRepoMockRecorder struct {
	mock *MockCacheRepo
}

// NewMockCacheRepo creates a new mock instance.
func NewMockCacheRepo(ctrl *gomock.Controller) *MockCacheRepo {
	mock := &MockCacheRepo{ctrl: ctrl}
	mock.recorder = &MockCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepo) EXPECT() *MockCacheRepoMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockCacheRepo) Del(ctx context.Context, id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", ctx, id)
}

// Del indicates an expected call of Del.
func (mr *MockCacheRepoMockRecorder) Del(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacheRepo)(nil).Del), ctx, id)
}

// MockCompMemberRepo is a mock of CompMemberRepo interface.
type MockCompMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompMemberRepoMockRecorder
}

// MockCompMemberRepoMockRecorder is the mock recorder for MockCompMemberRepo.
type MockCompMemberRepoMockRecorder struct {
	mock *MockCompMemberRepo
}

// NewMockCompMemberRepo creates a new mock instance.
func NewMockCompMemberRepo(ctrl *gomock.Controller) *MockCompMemberRepo {
	mock := &MockCompMemberRepo{ctrl: ctrl}
	mock.recorder = &MockCompMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompMemberRepo) EXPECT() *MockCompMemberRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCompMemberRepo) Get(ctx context.Context, userID, companyID uuid.UUID) (*member.CompanyMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, companyID)
	ret0, _ := ret[0].(*member.CompanyMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompMemberRepoMockRecorder) Get(ctx, userID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompMemberRepo)(nil).Get), ctx, userID, companyID)
}
