// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package archiveresume

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResumeRepo creates a new instance of MockResumeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResumeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResumeRepo {
	mock := &MockResumeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResumeRepo is an autogenerated mock type for the ResumeRepo type
type MockResumeRepo struct {
	mock.Mock
}

type MockResumeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResumeRepo) EXPECT() *MockResumeRepo_Expecter {
	return &MockResumeRepo_Expecter{mock: &_m.Mock}
}

// GetById provides a mock function for the type MockResumeRepo
func (_mock *MockResumeRepo) GetById(ctx context.Context, id uuid.UUID) (domain.Resume, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.Resume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Resume, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Resume); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Resume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResumeRepo_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockResumeRepo_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockResumeRepo_Expecter) GetById(ctx interface{}, id interface{}) *MockResumeRepo_GetById_Call {
	return &MockResumeRepo_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockResumeRepo_GetById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockResumeRepo_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResumeRepo_GetById_Call) Return(resume domain.Resume, err error) *MockResumeRepo_GetById_Call {
	_c.Call.Return(resume, err)
	return _c
}

func (_c *MockResumeRepo_GetById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Resume, error)) *MockResumeRepo_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// SetModerationStatus provides a mock function for the type MockResumeRepo
func (_mock *MockResumeRepo) SetModerationStatus(ctx context.Context, id uuid.UUID, status domain.ModerationStatus) error {
	ret := _mock.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for SetModerationStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ModerationStatus) error); ok {
		r0 = returnFunc(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockResumeRepo_SetModerationStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetModerationStatus'
type MockResumeRepo_SetModerationStatus_Call struct {
	*mock.Call
}

// SetModerationStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status domain.ModerationStatus
func (_e *MockResumeRepo_Expecter) SetModerationStatus(ctx interface{}, id interface{}, status interface{}) *MockResumeRepo_SetModerationStatus_Call {
	return &MockResumeRepo_SetModerationStatus_Call{Call: _e.mock.On("SetModerationStatus", ctx, id, status)}
}

func (_c *MockResumeRepo_SetModerationStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status domain.ModerationStatus)) *MockResumeRepo_SetModerationStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 domain.ModerationStatus
		if args[2] != nil {
			arg2 = args[2].(domain.ModerationStatus)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockResumeRepo_SetModerationStatus_Call) Return(err error) *MockResumeRepo_SetModerationStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockResumeRepo_SetModerationStatus_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, status domain.ModerationStatus) error) *MockResumeRepo_SetModerationStatus_Call {
	_c.Call.Return(run)
	return _c
}
