// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ResumeRepo is an autogenerated mock type for the ResumeRepo type
type ResumeRepo struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, resume
func (_m *ResumeRepo) Create(ctx context.Context, resume *domain.Resume) (uuid.UUID, error) {
	ret := _m.Called(ctx, resume)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Resume) (uuid.UUID, error)); ok {
		return rf(ctx, resume)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Resume) uuid.UUID); ok {
		r0 = rf(ctx, resume)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Resume) error); ok {
		r1 = rf(ctx, resume)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResumeRepo creates a new instance of ResumeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResumeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResumeRepo {
	mock := &ResumeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
