// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// SkillRepo is an autogenerated mock type for the SkillRepo type
type SkillRepo struct {
	mock.Mock
}

// AreSkillsExist provides a mock function with given fields: ctx, ids
func (_m *SkillRepo) AreSkillsExist(ctx context.Context, ids []uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for AreSkillsExist")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (bool, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []uuid.UUID) bool); ok {
		r0 = rf(ctx, ids)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSkillRepo creates a new instance of SkillRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSkillRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *SkillRepo {
	mock := &SkillRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
