// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package get_candidate_by_user_id

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCandidateRepo creates a new instance of MockCandidateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCandidateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCandidateRepo {
	mock := &MockCandidateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCandidateRepo is an autogenerated mock type for the CandidateRepo type
type MockCandidateRepo struct {
	mock.Mock
}

type MockCandidateRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCandidateRepo) EXPECT() *MockCandidateRepo_Expecter {
	return &MockCandidateRepo_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function for the type MockCandidateRepo
func (_mock *MockCandidateRepo) GetByUserID(ctx context.Context, id uuid.UUID) (domain.Candidate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 domain.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Candidate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Candidate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCandidateRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockCandidateRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCandidateRepo_Expecter) GetByUserID(ctx interface{}, id interface{}) *MockCandidateRepo_GetByUserID_Call {
	return &MockCandidateRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, id)}
}

func (_c *MockCandidateRepo_GetByUserID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCandidateRepo_GetByUserID_Call) Return(candidate domain.Candidate, err error) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Return(candidate, err)
	return _c
}

func (_c *MockCandidateRepo_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Candidate, error)) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}
