// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package get_resume

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResumeRepo creates a new instance of MockResumeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResumeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResumeRepo {
	mock := &MockResumeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResumeRepo is an autogenerated mock type for the ResumeRepo type
type MockResumeRepo struct {
	mock.Mock
}

type MockResumeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResumeRepo) EXPECT() *MockResumeRepo_Expecter {
	return &MockResumeRepo_Expecter{mock: &_m.Mock}
}

// GetByCandidateId provides a mock function for the type MockResumeRepo
func (_mock *MockResumeRepo) GetByCandidateId(ctx context.Context, candidateId uuid.UUID, page int, size int) ([]domain.Resume, error) {
	ret := _mock.Called(ctx, candidateId, page, size)

	if len(ret) == 0 {
		panic("no return value specified for GetByCandidateId")
	}

	var r0 []domain.Resume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]domain.Resume, error)); ok {
		return returnFunc(ctx, candidateId, page, size)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []domain.Resume); ok {
		r0 = returnFunc(ctx, candidateId, page, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Resume)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, candidateId, page, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResumeRepo_GetByCandidateId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCandidateId'
type MockResumeRepo_GetByCandidateId_Call struct {
	*mock.Call
}

// GetByCandidateId is a helper method to define mock.On call
//   - ctx context.Context
//   - candidateId uuid.UUID
//   - page int
//   - size int
func (_e *MockResumeRepo_Expecter) GetByCandidateId(ctx interface{}, candidateId interface{}, page interface{}, size interface{}) *MockResumeRepo_GetByCandidateId_Call {
	return &MockResumeRepo_GetByCandidateId_Call{Call: _e.mock.On("GetByCandidateId", ctx, candidateId, page, size)}
}

func (_c *MockResumeRepo_GetByCandidateId_Call) Run(run func(ctx context.Context, candidateId uuid.UUID, page int, size int)) *MockResumeRepo_GetByCandidateId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockResumeRepo_GetByCandidateId_Call) Return(resumes []domain.Resume, err error) *MockResumeRepo_GetByCandidateId_Call {
	_c.Call.Return(resumes, err)
	return _c
}

func (_c *MockResumeRepo_GetByCandidateId_Call) RunAndReturn(run func(ctx context.Context, candidateId uuid.UUID, page int, size int) ([]domain.Resume, error)) *MockResumeRepo_GetByCandidateId_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockResumeRepo
func (_mock *MockResumeRepo) GetById(ctx context.Context, id uuid.UUID) (domain.Resume, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.Resume
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Resume, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Resume); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Resume)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResumeRepo_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockResumeRepo_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockResumeRepo_Expecter) GetById(ctx interface{}, id interface{}) *MockResumeRepo_GetById_Call {
	return &MockResumeRepo_GetById_Call{Call: _e.mock.On("GetById", ctx, id)}
}

func (_c *MockResumeRepo_GetById_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockResumeRepo_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResumeRepo_GetById_Call) Return(resume domain.Resume, err error) *MockResumeRepo_GetById_Call {
	_c.Call.Return(resume, err)
	return _c
}

func (_c *MockResumeRepo_GetById_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Resume, error)) *MockResumeRepo_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCandidateRepo creates a new instance of MockCandidateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCandidateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCandidateRepo {
	mock := &MockCandidateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCandidateRepo is an autogenerated mock type for the CandidateRepo type
type MockCandidateRepo struct {
	mock.Mock
}

type MockCandidateRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCandidateRepo) EXPECT() *MockCandidateRepo_Expecter {
	return &MockCandidateRepo_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function for the type MockCandidateRepo
func (_mock *MockCandidateRepo) GetByUserID(ctx context.Context, id uuid.UUID) (domain.Candidate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 domain.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Candidate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Candidate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCandidateRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockCandidateRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCandidateRepo_Expecter) GetByUserID(ctx interface{}, id interface{}) *MockCandidateRepo_GetByUserID_Call {
	return &MockCandidateRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, id)}
}

func (_c *MockCandidateRepo_GetByUserID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCandidateRepo_GetByUserID_Call) Return(candidate domain.Candidate, err error) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Return(candidate, err)
	return _c
}

func (_c *MockCandidateRepo_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Candidate, error)) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}
