// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package get_skill

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillRepo creates a new instance of MockSkillRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillRepo {
	mock := &MockSkillRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillRepo is an autogenerated mock type for the SkillRepo type
type MockSkillRepo struct {
	mock.Mock
}

type MockSkillRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillRepo) EXPECT() *MockSkillRepo_Expecter {
	return &MockSkillRepo_Expecter{mock: &_m.Mock}
}

// GetByID provides a mock function for the type MockSkillRepo
func (_mock *MockSkillRepo) GetByID(ctx context.Context, id uuid.UUID) (domain.Skill, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Skill, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Skill); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Skill)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockSkillRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSkillRepo_Expecter) GetByID(ctx interface{}, id interface{}) *MockSkillRepo_GetByID_Call {
	return &MockSkillRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockSkillRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSkillRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillRepo_GetByID_Call) Return(skill domain.Skill, err error) *MockSkillRepo_GetByID_Call {
	_c.Call.Return(skill, err)
	return _c
}

func (_c *MockSkillRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Skill, error)) *MockSkillRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSkillRepo
func (_mock *MockSkillRepo) List(ctx context.Context) ([]domain.Skill, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Skill
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Skill, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Skill); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Skill)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillRepo_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSkillRepo_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSkillRepo_Expecter) List(ctx interface{}) *MockSkillRepo_List_Call {
	return &MockSkillRepo_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockSkillRepo_List_Call) Run(run func(ctx context.Context)) *MockSkillRepo_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSkillRepo_List_Call) Return(skills []domain.Skill, err error) *MockSkillRepo_List_Call {
	_c.Call.Return(skills, err)
	return _c
}

func (_c *MockSkillRepo_List_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Skill, error)) *MockSkillRepo_List_Call {
	_c.Call.Return(run)
	return _c
}
