// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ResumeRepo is an autogenerated mock type for the ResumeRepo type
type ResumeRepo struct {
	mock.Mock
}

// GetByCandidateId provides a mock function with given fields: ctx, candidateId
func (_m *ResumeRepo) GetByCandidateId(ctx context.Context, candidateId uuid.UUID) ([]domain.Resume, error) {
	ret := _m.Called(ctx, candidateId)

	if len(ret) == 0 {
		panic("no return value specified for GetByCandidateId")
	}

	var r0 []domain.Resume
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]domain.Resume, error)); ok {
		return rf(ctx, candidateId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []domain.Resume); ok {
		r0 = rf(ctx, candidateId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Resume)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, candidateId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: ctx, id
func (_m *ResumeRepo) GetById(ctx context.Context, id uuid.UUID) (domain.Resume, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 domain.Resume
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Resume, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Resume); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Resume)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewResumeRepo creates a new instance of ResumeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResumeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResumeRepo {
	mock := &ResumeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
