events {}

http {
    gzip on;
    gzip_types application/json;

    client_max_body_size 10M;

    # rate limiting
    limit_req_status 429;
    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=20r/s;
    limit_req_zone $binary_remote_addr zone=auth_limit:10m rate=10r/m;

    # logging
    log_format api_gateway
        '$remote_addr [$time_local] '
        '"$request" $status '
        'rt=$request_time '
        'urt="$upstream_response_time" '
        '"$http_user_agent"';

    access_log /dev/stdout api_gateway;
    error_log /dev/stderr warn;

    # upstreams (for load balancing having multiple instances)
    upstream candidate_backend {
        server candidate-service:8081;
        keepalive 32;
    }

    upstream company_backend {
        server company-service:8080;
        keepalive 32;
    }

    upstream application_backend {
        server application-service:8080;
        keepalive 32;
    }

    upstream auth_backend {
        server auth-service:8000;
        keepalive 32;
    }

    # http -> https redirect
    server {
        listen 80;

        server_name api.traineematch.space;

        return 301 https://$host$request_uri;
    }

    # https api gw
    server {
        listen 443 ssl;
        http2 on;

        # ssl + domain
        server_name api.traineematch.space;
        ssl_certificate /etc/letsencrypt/live/api.traineematch.space/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.traineematch.space/privkey.pem;

        limit_req zone=api_limit burst=30 nodelay;

        # timeouts
        proxy_connect_timeout 10s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        # Candidate service
        location /api/candidate/ {
            rewrite ^/api/candidate/(.*)$ /api/v1/$1 break;

            proxy_pass http://candidate_backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Company service
        location /api/company/ {
            rewrite ^/api/company/(.*)$ /api/v1/$1 break;

            proxy_pass http://company_backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Application service
        location /api/application/ {
            rewrite ^/api/application/(.*)$ /api/v1/$1 break;

            proxy_pass http://application_backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Auth service
        location /api/auth/ {
            limit_req zone=auth_limit burst=10 nodelay;

            rewrite ^/api/auth/(.*)$ /api/v1/auth/$1 break;

            proxy_pass http://auth_backend;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Healthcheck
        location = /health {
            access_log off;
            add_header Content-Type text/plain;
            return 200 "ok";
        }
    }
}
