events {}

http {
    server {
        listen 80;

        server_name api.traineematch.space;

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;

        server_name api.traineematch.space;

        ssl_certificate /etc/letsencrypt/live/api.traineematch.space/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/api.traineematch.space/privkey.pem;

        # Healthcheck
        location /health {
            return 200 "ok";
        }
    }
}
