// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	company "github.com/HghaVlad/trainee-match/backend/company/internal/domain/company"
	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	vacancy "github.com/HghaVlad/trainee-match/backend/company/internal/domain/vacancy"
	views "github.com/HghaVlad/trainee-match/backend/company/internal/usecase/vacancy/views"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockVacancyRepo is a mock of VacancyRepo interface.
type MockVacancyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVacancyRepoMockRecorder
}

// MockVacancyRepoMockRecorder is the mock recorder for MockVacancyRepo.
type MockVacancyRepoMockRecorder struct {
	mock *MockVacancyRepo
}

// NewMockVacancyRepo creates a new mock instance.
func NewMockVacancyRepo(ctrl *gomock.Controller) *MockVacancyRepo {
	mock := &MockVacancyRepo{ctrl: ctrl}
	mock.recorder = &MockVacancyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVacancyRepo) EXPECT() *MockVacancyRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVacancyRepo) Create(ctx context.Context, vacancy *vacancy.Vacancy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, vacancy)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVacancyRepoMockRecorder) Create(ctx, vacancy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVacancyRepo)(nil).Create), ctx, vacancy)
}

// MockCompMemberRepo is a mock of CompMemberRepo interface.
type MockCompMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompMemberRepoMockRecorder
}

// MockCompMemberRepoMockRecorder is the mock recorder for MockCompMemberRepo.
type MockCompMemberRepoMockRecorder struct {
	mock *MockCompMemberRepo
}

// NewMockCompMemberRepo creates a new mock instance.
func NewMockCompMemberRepo(ctrl *gomock.Controller) *MockCompMemberRepo {
	mock := &MockCompMemberRepo{ctrl: ctrl}
	mock.recorder = &MockCompMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompMemberRepo) EXPECT() *MockCompMemberRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCompMemberRepo) Get(ctx context.Context, userID, companyID uuid.UUID) (*member.CompanyMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, companyID)
	ret0, _ := ret[0].(*member.CompanyMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompMemberRepoMockRecorder) Get(ctx, userID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompMemberRepo)(nil).Get), ctx, userID, companyID)
}

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// GetByMember mocks base method.
func (m *MockCompanyRepo) GetByMember(ctx context.Context, id, userID uuid.UUID) (*company.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMember", ctx, id, userID)
	ret0, _ := ret[0].(*company.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMember indicates an expected call of GetByMember.
func (mr *MockCompanyRepoMockRecorder) GetByMember(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMember", reflect.TypeOf((*MockCompanyRepo)(nil).GetByMember), ctx, id, userID)
}

// MockSearchRepo is a mock of SearchRepo interface.
type MockSearchRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRepoMockRecorder
}

// MockSearchRepoMockRecorder is the mock recorder for MockSearchRepo.
type MockSearchRepoMockRecorder struct {
	mock *MockSearchRepo
}

// NewMockSearchRepo creates a new mock instance.
func NewMockSearchRepo(ctrl *gomock.Controller) *MockSearchRepo {
	mock := &MockSearchRepo{ctrl: ctrl}
	mock.recorder = &MockSearchRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRepo) EXPECT() *MockSearchRepoMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MockSearchRepo) Index(ctx context.Context, vac views.VacancySearch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, vac)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockSearchRepoMockRecorder) Index(ctx, vac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockSearchRepo)(nil).Index), ctx, vac)
}
