// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination=mocks/port_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	company "github.com/HghaVlad/trainee-match/backend/company/internal/domain/company"
	vacancy "github.com/HghaVlad/trainee-match/backend/company/internal/domain/vacancy"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVacancyRepo is a mock of VacancyRepo interface.
type MockVacancyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVacancyRepoMockRecorder
	isgomock struct{}
}

// MockVacancyRepoMockRecorder is the mock recorder for MockVacancyRepo.
type MockVacancyRepoMockRecorder struct {
	mock *MockVacancyRepo
}

// NewMockVacancyRepo creates a new mock instance.
func NewMockVacancyRepo(ctrl *gomock.Controller) *MockVacancyRepo {
	mock := &MockVacancyRepo{ctrl: ctrl}
	mock.recorder = &MockVacancyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVacancyRepo) EXPECT() *MockVacancyRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockVacancyRepo) Create(ctx context.Context, arg1 *vacancy.Vacancy) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVacancyRepoMockRecorder) Create(ctx, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVacancyRepo)(nil).Create), ctx, arg1)
}

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
	isgomock struct{}
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// GetByMember mocks base method.
func (m *MockCompanyRepo) GetByMember(ctx context.Context, id, userID uuid.UUID) (*company.Company, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMember", ctx, id, userID)
	ret0, _ := ret[0].(*company.Company)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMember indicates an expected call of GetByMember.
func (mr *MockCompanyRepoMockRecorder) GetByMember(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMember", reflect.TypeOf((*MockCompanyRepo)(nil).GetByMember), ctx, id, userID)
}

// MockoutboxWriter is a mock of outboxWriter interface.
type MockoutboxWriter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxWriterMockRecorder
	isgomock struct{}
}

// MockoutboxWriterMockRecorder is the mock recorder for MockoutboxWriter.
type MockoutboxWriterMockRecorder struct {
	mock *MockoutboxWriter
}

// NewMockoutboxWriter creates a new mock instance.
func NewMockoutboxWriter(ctrl *gomock.Controller) *MockoutboxWriter {
	mock := &MockoutboxWriter{ctrl: ctrl}
	mock.recorder = &MockoutboxWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxWriter) EXPECT() *MockoutboxWriterMockRecorder {
	return m.recorder
}

// WriteVacancyDraftCreated mocks base method.
func (m *MockoutboxWriter) WriteVacancyDraftCreated(ctx context.Context, ev vacancy.DraftCreatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteVacancyDraftCreated", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteVacancyDraftCreated indicates an expected call of WriteVacancyDraftCreated.
func (mr *MockoutboxWriterMockRecorder) WriteVacancyDraftCreated(ctx, ev any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteVacancyDraftCreated", reflect.TypeOf((*MockoutboxWriter)(nil).WriteVacancyDraftCreated), ctx, ev)
}
