// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package create_resume

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain/events"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockResumeRepo creates a new instance of MockResumeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResumeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResumeRepo {
	mock := &MockResumeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockResumeRepo is an autogenerated mock type for the ResumeRepo type
type MockResumeRepo struct {
	mock.Mock
}

type MockResumeRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResumeRepo) EXPECT() *MockResumeRepo_Expecter {
	return &MockResumeRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockResumeRepo
func (_mock *MockResumeRepo) Create(ctx context.Context, resume *domain.Resume) (uuid.UUID, error) {
	ret := _mock.Called(ctx, resume)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Resume) (uuid.UUID, error)); ok {
		return returnFunc(ctx, resume)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Resume) uuid.UUID); ok {
		r0 = returnFunc(ctx, resume)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *domain.Resume) error); ok {
		r1 = returnFunc(ctx, resume)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockResumeRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockResumeRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - resume *domain.Resume
func (_e *MockResumeRepo_Expecter) Create(ctx interface{}, resume interface{}) *MockResumeRepo_Create_Call {
	return &MockResumeRepo_Create_Call{Call: _e.mock.On("Create", ctx, resume)}
}

func (_c *MockResumeRepo_Create_Call) Run(run func(ctx context.Context, resume *domain.Resume)) *MockResumeRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Resume
		if args[1] != nil {
			arg1 = args[1].(*domain.Resume)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockResumeRepo_Create_Call) Return(uUID uuid.UUID, err error) *MockResumeRepo_Create_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockResumeRepo_Create_Call) RunAndReturn(run func(ctx context.Context, resume *domain.Resume) (uuid.UUID, error)) *MockResumeRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSkillRepo creates a new instance of MockSkillRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillRepo {
	mock := &MockSkillRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillRepo is an autogenerated mock type for the SkillRepo type
type MockSkillRepo struct {
	mock.Mock
}

type MockSkillRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillRepo) EXPECT() *MockSkillRepo_Expecter {
	return &MockSkillRepo_Expecter{mock: &_m.Mock}
}

// AreSkillsExist provides a mock function for the type MockSkillRepo
func (_mock *MockSkillRepo) AreSkillsExist(ctx context.Context, ids []uuid.UUID) (bool, error) {
	ret := _mock.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for AreSkillsExist")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (bool, error)); ok {
		return returnFunc(ctx, ids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) bool); ok {
		r0 = returnFunc(ctx, ids)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSkillRepo_AreSkillsExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AreSkillsExist'
type MockSkillRepo_AreSkillsExist_Call struct {
	*mock.Call
}

// AreSkillsExist is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []uuid.UUID
func (_e *MockSkillRepo_Expecter) AreSkillsExist(ctx interface{}, ids interface{}) *MockSkillRepo_AreSkillsExist_Call {
	return &MockSkillRepo_AreSkillsExist_Call{Call: _e.mock.On("AreSkillsExist", ctx, ids)}
}

func (_c *MockSkillRepo_AreSkillsExist_Call) Run(run func(ctx context.Context, ids []uuid.UUID)) *MockSkillRepo_AreSkillsExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillRepo_AreSkillsExist_Call) Return(b bool, err error) *MockSkillRepo_AreSkillsExist_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockSkillRepo_AreSkillsExist_Call) RunAndReturn(run func(ctx context.Context, ids []uuid.UUID) (bool, error)) *MockSkillRepo_AreSkillsExist_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCandidateRepo creates a new instance of MockCandidateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCandidateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCandidateRepo {
	mock := &MockCandidateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCandidateRepo is an autogenerated mock type for the CandidateRepo type
type MockCandidateRepo struct {
	mock.Mock
}

type MockCandidateRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCandidateRepo) EXPECT() *MockCandidateRepo_Expecter {
	return &MockCandidateRepo_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function for the type MockCandidateRepo
func (_mock *MockCandidateRepo) GetByUserID(ctx context.Context, id uuid.UUID) (domain.Candidate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 domain.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Candidate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Candidate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCandidateRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockCandidateRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCandidateRepo_Expecter) GetByUserID(ctx interface{}, id interface{}) *MockCandidateRepo_GetByUserID_Call {
	return &MockCandidateRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, id)}
}

func (_c *MockCandidateRepo_GetByUserID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCandidateRepo_GetByUserID_Call) Return(candidate domain.Candidate, err error) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Return(candidate, err)
	return _c
}

func (_c *MockCandidateRepo_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Candidate, error)) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventWriter creates a new instance of MockEventWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventWriter {
	mock := &MockEventWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventWriter is an autogenerated mock type for the EventWriter type
type MockEventWriter struct {
	mock.Mock
}

type MockEventWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventWriter) EXPECT() *MockEventWriter_Expecter {
	return &MockEventWriter_Expecter{mock: &_m.Mock}
}

// WriteResumeUpserted provides a mock function for the type MockEventWriter
func (_mock *MockEventWriter) WriteResumeUpserted(ctx context.Context, ev events.ResumeUpserted) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for WriteResumeUpserted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.ResumeUpserted) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventWriter_WriteResumeUpserted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteResumeUpserted'
type MockEventWriter_WriteResumeUpserted_Call struct {
	*mock.Call
}

// WriteResumeUpserted is a helper method to define mock.On call
//   - ctx context.Context
//   - ev events.ResumeUpserted
func (_e *MockEventWriter_Expecter) WriteResumeUpserted(ctx interface{}, ev interface{}) *MockEventWriter_WriteResumeUpserted_Call {
	return &MockEventWriter_WriteResumeUpserted_Call{Call: _e.mock.On("WriteResumeUpserted", ctx, ev)}
}

func (_c *MockEventWriter_WriteResumeUpserted_Call) Run(run func(ctx context.Context, ev events.ResumeUpserted)) *MockEventWriter_WriteResumeUpserted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 events.ResumeUpserted
		if args[1] != nil {
			arg1 = args[1].(events.ResumeUpserted)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventWriter_WriteResumeUpserted_Call) Return(err error) *MockEventWriter_WriteResumeUpserted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventWriter_WriteResumeUpserted_Call) RunAndReturn(run func(ctx context.Context, ev events.ResumeUpserted) error) *MockEventWriter_WriteResumeUpserted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrManager creates a new instance of MockTrManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrManager {
	mock := &MockTrManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrManager is an autogenerated mock type for the TrManager type
type MockTrManager struct {
	mock.Mock
}

type MockTrManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrManager) EXPECT() *MockTrManager_Expecter {
	return &MockTrManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockTrManager
func (_mock *MockTrManager) Do(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockTrManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTrManager_Expecter) Do(ctx interface{}, fn interface{}) *MockTrManager_Do_Call {
	return &MockTrManager_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *MockTrManager_Do_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTrManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrManager_Do_Call) Return(err error) *MockTrManager_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrManager_Do_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTrManager_Do_Call {
	_c.Call.Return(run)
	return _c
}
