// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/companies": {
            "get": {
                "description": "Uses cursor pagination, returns next cursor if there's more. Supports order by vacancies_desc, created_at_desc, name_asc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "List company summaries",
                "parameters": [
                    {
                        "type": "string",
                        "default": "vacancies_desc",
                        "description": "Order attribute",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Items per page",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates new company, returns id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "Create new company",
                "parameters": [
                    {
                        "description": "Request to create a company",
                        "name": "company_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/companies/{company-id}/vacancies": {
            "get": {
                "description": "Uses cursor pagination, returns next cursor if there's more. Supports order by published_at_desc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vacancy"
                ],
                "summary": "Lists company's vacancy summaries",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID (UUID)",
                        "name": "company-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "published_at_desc",
                        "description": "Order attribute",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyByCompListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates new vacancy, returns id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vacancy"
                ],
                "summary": "Create new vacancy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID (UUID)",
                        "name": "company-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request to create vacancy",
                        "name": "vacancy_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyCreatedResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/companies/{company-id}/vacancies/{vacancy-id}": {
            "get": {
                "description": "Returns vacancy by id, company id should be correct, otherwise it's 404",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vacancy"
                ],
                "summary": "Get vacancy by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID (UUID)",
                        "name": "company-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Vacancy ID (UUID)",
                        "name": "vacancy-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes vacancy by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vacancy"
                ],
                "summary": "Delete vacancy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Vacancy ID",
                        "name": "vacancy-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company-id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates vacancy fields. Nil fields are ignored (not updated).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vacancy"
                ],
                "summary": "Update vacancy",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "company-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Vacancy ID",
                        "name": "vacancy-id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Vacancy update payload",
                        "name": "vacancy_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Vacancy updated successfully"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/companies/{id}": {
            "get": {
                "description": "Returns company profile by UUID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "Get profile by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes company by id",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "Delete company",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "description": "Partially updates company fields, if field not provided or null - it won't be changed",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "company"
                ],
                "summary": "Update company",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Company ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Request to update company",
                        "name": "company_request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vacancies": {
            "get": {
                "description": "Uses cursor pagination, returns next cursor if there's more. Supports order by published_at_desc",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vacancy"
                ],
                "summary": "List vacancy summaries",
                "parameters": [
                    {
                        "type": "string",
                        "default": "published_at_desc",
                        "description": "Order attribute",
                        "name": "order",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor",
                        "name": "cursor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Items per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responds.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "We make the world a better place"
                },
                "name": {
                    "type": "string",
                    "example": "Google Inc."
                },
                "website": {
                    "type": "string",
                    "example": "https://www.google.com"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreatedResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyListItemResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "logoUrl": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "openVacanciesCount": {
                    "type": "integer"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyListResponse": {
            "type": "object",
            "properties": {
                "companies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyListItemResponse"
                    }
                },
                "nextCursor": {
                    "type": "string"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string",
                    "example": "2020-04-08T21:00:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "We make the world a better place"
                },
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "logoURL": {
                    "type": "string",
                    "example": "http://domain/minio/6icinimmck...mksk"
                },
                "name": {
                    "type": "string",
                    "example": "Google Inc."
                },
                "openVacanciesCount": {
                    "type": "integer",
                    "example": 13
                },
                "ownerId": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2020-04-08T21:00:00Z"
                },
                "website": {
                    "type": "string",
                    "example": "https://www.google.com"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyUpdateRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "New description"
                },
                "name": {
                    "type": "string",
                    "example": "Google LLC"
                },
                "website": {
                    "type": "string",
                    "example": "https://google.com"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyByCompListItemResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Mountain View"
                },
                "employmentType": {
                    "type": "string",
                    "example": "internship,full_time,part_time"
                },
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "isPaid": {
                    "type": "boolean",
                    "example": true
                },
                "publishedAt": {
                    "type": "string",
                    "example": "2026-01-18T09:30:00Z"
                },
                "salaryFrom": {
                    "type": "integer",
                    "example": 3500
                },
                "salaryTo": {
                    "type": "integer",
                    "example": 5000
                },
                "title": {
                    "type": "string",
                    "example": "Go Backend Developer Intern"
                },
                "workFormat": {
                    "type": "string",
                    "example": "hybrid"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyByCompListResponse": {
            "type": "object",
            "properties": {
                "nextCursor": {
                    "type": "string"
                },
                "vacancies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyByCompListItemResponse"
                    }
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyCreateRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Mountain View"
                },
                "description": {
                    "type": "string",
                    "example": "Join Google's backend team to build scalable services in Go."
                },
                "duration_from_months": {
                    "type": "integer",
                    "example": 3
                },
                "duration_to_months": {
                    "type": "integer",
                    "example": 6
                },
                "employment_type": {
                    "type": "string",
                    "example": "internship"
                },
                "flexible_schedule": {
                    "type": "boolean"
                },
                "hours_per_week_from": {
                    "type": "integer",
                    "example": 20
                },
                "hours_per_week_to": {
                    "type": "integer",
                    "example": 40
                },
                "internship_to_offer": {
                    "type": "boolean"
                },
                "is_paid": {
                    "type": "boolean"
                },
                "salary_from": {
                    "type": "integer",
                    "example": 1000
                },
                "salary_to": {
                    "type": "integer",
                    "example": 1500
                },
                "title": {
                    "type": "string",
                    "example": "Go Backend Developer Intern"
                },
                "work_format": {
                    "type": "string",
                    "enum": [
                        "onsite",
                        "remote",
                        "hybrid"
                    ],
                    "example": "hybrid"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyCreatedResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyListItemResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Mountain View"
                },
                "companyId": {
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                },
                "companyName": {
                    "type": "string",
                    "example": "Google Inc."
                },
                "employmentType": {
                    "type": "string",
                    "example": "internship,full_time,part_time"
                },
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "isPaid": {
                    "type": "boolean",
                    "example": true
                },
                "publishedAt": {
                    "type": "string",
                    "example": "2026-01-18T09:30:00Z"
                },
                "salaryFrom": {
                    "type": "integer",
                    "example": 3500
                },
                "salaryTo": {
                    "type": "integer",
                    "example": 5000
                },
                "title": {
                    "type": "string",
                    "example": "Go Backend Developer Intern"
                },
                "workFormat": {
                    "type": "string",
                    "example": "hybrid"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyListResponse": {
            "type": "object",
            "properties": {
                "nextCursor": {
                    "type": "string"
                },
                "vacancies": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyListItemResponse"
                    }
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyResponse": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Mountain View"
                },
                "company_id": {
                    "type": "string",
                    "example": "d290f1ee-6c54-4b01-90e6-d701748f0851"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-01-18T09:30:00Z"
                },
                "description": {
                    "type": "string",
                    "example": "Join Google's backend team to build scalable services in Go."
                },
                "duration_from_months": {
                    "type": "integer",
                    "example": 3
                },
                "duration_to_months": {
                    "type": "integer",
                    "example": 6
                },
                "employment_type": {
                    "type": "string",
                    "enum": [
                        "internship",
                        "full_time",
                        "part_time"
                    ],
                    "example": "internship"
                },
                "flexible_schedule": {
                    "type": "boolean",
                    "example": true
                },
                "hours_per_week_from": {
                    "type": "integer",
                    "example": 30
                },
                "hours_per_week_to": {
                    "type": "integer",
                    "example": 40
                },
                "id": {
                    "type": "string",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "internship_to_offer": {
                    "type": "boolean",
                    "example": true
                },
                "is_active": {
                    "type": "boolean",
                    "example": true
                },
                "is_paid": {
                    "type": "boolean",
                    "example": true
                },
                "published_at": {
                    "type": "string",
                    "example": "2026-01-20T10:00:00Z"
                },
                "salary_from": {
                    "type": "integer",
                    "example": 3500
                },
                "salary_to": {
                    "type": "integer",
                    "example": 5000
                },
                "title": {
                    "type": "string",
                    "example": "Go Backend Developer Intern"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-01-22T14:15:00Z"
                },
                "work_format": {
                    "type": "string",
                    "enum": [
                        "onsite",
                        "remote",
                        "hybrid"
                    ],
                    "example": "hybrid"
                }
            }
        },
        "github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyUpdateRequest": {
            "type": "object",
            "properties": {
                "city": {
                    "type": "string",
                    "example": "Berlin"
                },
                "description": {
                    "type": "string",
                    "example": "Work on high-load backend services using Go and PostgreSQL."
                },
                "duration_from_months": {
                    "type": "integer",
                    "example": 3
                },
                "duration_to_months": {
                    "type": "integer",
                    "example": 6
                },
                "employment_type": {
                    "type": "string",
                    "enum": [
                        "internship",
                        "full_time",
                        "part_time"
                    ],
                    "example": "internship"
                },
                "flexible_schedule": {
                    "type": "boolean",
                    "example": true
                },
                "hours_per_week_from": {
                    "type": "integer",
                    "example": 20
                },
                "hours_per_week_to": {
                    "type": "integer",
                    "example": 40
                },
                "internship_to_offer": {
                    "type": "boolean",
                    "example": true
                },
                "is_paid": {
                    "type": "boolean",
                    "example": true
                },
                "salary_from": {
                    "type": "integer",
                    "example": 1000
                },
                "salary_to": {
                    "type": "integer",
                    "example": 1500
                },
                "title": {
                    "type": "string",
                    "example": "Go Backend Developer Intern"
                },
                "work_format": {
                    "type": "string",
                    "enum": [
                        "onsite",
                        "remote",
                        "hybrid"
                    ],
                    "example": "remote"
                }
            }
        },
        "responds.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "order not found: id=550e8400-e29b-41d4-a716-446655440000"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Trainee Match: Company Service API",
	Description:      "company microservice",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
