basePath: /api/v1
definitions:
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreateRequest:
    properties:
      description:
        example: We make the world a better place
        type: string
      name:
        example: Google Inc.
        type: string
      website:
        example: https://www.google.com
        type: string
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreatedResponse:
    properties:
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyResponse:
    properties:
      createdAt:
        example: "2020-04-08T21:00:00Z"
        type: string
      description:
        example: We make the world a better place
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      logoURL:
        example: http://domain/minio/6icinimmck...mksk
        type: string
      name:
        example: Google Inc.
        type: string
      ownerId:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      updatedAt:
        example: "2020-04-08T21:00:00Z"
        type: string
      website:
        example: https://www.google.com
        type: string
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyUpdateRequest:
    properties:
      description:
        example: New description
        type: string
      name:
        example: Google LLC
        type: string
      website:
        example: https://google.com
        type: string
    type: object
  responds.ErrorResponse:
    properties:
      error:
        example: 'order not found: id=550e8400-e29b-41d4-a716-446655440000'
        type: string
    type: object
info:
  contact: {}
  description: company microservice
  title: 'Trainee Match: Company Service API'
  version: "1.0"
paths:
  /companies:
    post:
      consumes:
      - application/json
      description: Creates new company, returns id
      parameters:
      - description: Request to create a company
        in: body
        name: company_request
        required: true
        schema:
          $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: Create new company
      tags:
      - company
  /companies/{id}:
    get:
      consumes:
      - application/json
      description: Returns company profile by UUID
      parameters:
      - description: Company ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: Get profile by id
      tags:
      - company
    patch:
      consumes:
      - application/json
      description: Partially updates company fields
      parameters:
      - description: Company ID
        in: path
        name: id
        required: true
        type: string
      - description: Request to update company
        in: body
        name: company_request
        required: true
        schema:
          $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyUpdateRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: Update company
      tags:
      - company
schemes:
- http
- https
swagger: "2.0"
