basePath: /api/v1
definitions:
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreateRequest:
    properties:
      description:
        example: We make the world a better place
        type: string
      name:
        example: Google Inc.
        type: string
      website:
        example: https://www.google.com
        type: string
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreatedResponse:
    properties:
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyListItemResponse:
    properties:
      id:
        type: string
      logoUrl:
        type: string
      name:
        type: string
      openVacanciesCount:
        type: integer
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyListResponse:
    properties:
      companies:
        items:
          $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyListItemResponse'
        type: array
      nextCursor:
        type: string
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyResponse:
    properties:
      createdAt:
        example: "2020-04-08T21:00:00Z"
        type: string
      description:
        example: We make the world a better place
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      logoURL:
        example: http://domain/minio/6icinimmck...mksk
        type: string
      name:
        example: Google Inc.
        type: string
      openVacanciesCount:
        example: 13
        type: integer
      ownerId:
        example: 550e8400-e29b-41d4-a716-446655440000
        type: string
      updatedAt:
        example: "2020-04-08T21:00:00Z"
        type: string
      website:
        example: https://www.google.com
        type: string
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyUpdateRequest:
    properties:
      description:
        example: New description
        type: string
      name:
        example: Google LLC
        type: string
      website:
        example: https://google.com
        type: string
    type: object
  github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyResponse:
    properties:
      city:
        example: Mountain View
        type: string
      company_id:
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
        type: string
      created_at:
        example: "2026-01-18T09:30:00Z"
        type: string
      description:
        example: Join Google's backend team to build scalable services in Go.
        type: string
      duration_from_months:
        example: 3
        type: integer
      duration_to_months:
        example: 6
        type: integer
      employment_type:
        enum:
        - internship
        - full_time
        - part_time
        example: internship
        type: string
      flexible_schedule:
        example: true
        type: boolean
      hours_per_week_from:
        example: 30
        type: integer
      hours_per_week_to:
        example: 40
        type: integer
      id:
        example: 3fa85f64-5717-4562-b3fc-2c963f66afa6
        type: string
      internship_to_offer:
        example: true
        type: boolean
      is_active:
        example: true
        type: boolean
      is_paid:
        example: true
        type: boolean
      published_at:
        example: "2026-01-20T10:00:00Z"
        type: string
      salary_from:
        example: 3500
        type: integer
      salary_to:
        example: 5000
        type: integer
      title:
        example: Go Backend Developer Intern
        type: string
      updated_at:
        example: "2026-01-22T14:15:00Z"
        type: string
      work_format:
        enum:
        - onsite
        - remote
        - hybrid
        example: hybrid
        type: string
    type: object
  responds.ErrorResponse:
    properties:
      error:
        example: 'order not found: id=550e8400-e29b-41d4-a716-446655440000'
        type: string
    type: object
info:
  contact: {}
  description: company microservice
  title: 'Trainee Match: Company Service API'
  version: "1.0"
paths:
  /companies:
    get:
      consumes:
      - application/json
      description: Uses cursor pagination, returns next cursor if there's more. Supports
        order by vacancies_desc, created_at_desc, name_asc
      parameters:
      - default: vacancies_desc
        description: Order attribute
        in: query
        name: order
        type: string
      - description: Items per page
        in: query
        name: cursor
        type: string
      - default: 20
        description: Items per page
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyListResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: List company summaries
      tags:
      - company
    post:
      consumes:
      - application/json
      description: Creates new company, returns id
      parameters:
      - description: Request to create a company
        in: body
        name: company_request
        required: true
        schema:
          $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyCreatedResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: Create new company
      tags:
      - company
  /companies/{company-id}/vacancies/{vacancy-id}:
    get:
      consumes:
      - application/json
      description: Returns vacancy by id, company id should be correct, otherwise
        it's 404
      parameters:
      - description: Company ID (UUID)
        in: path
        name: company-id
        required: true
        type: string
      - description: Vacancy ID (UUID)
        in: path
        name: vacancy-id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.VacancyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: Get vacancy by id
      tags:
      - vacancy
  /companies/{id}:
    delete:
      description: Deletes company by id
      parameters:
      - description: Company ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: Delete company
      tags:
      - company
    get:
      consumes:
      - application/json
      description: Returns company profile by UUID
      parameters:
      - description: Company ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: Get profile by id
      tags:
      - company
    patch:
      consumes:
      - application/json
      description: Partially updates company fields, if field not provided or null
        - it won't be changed
      parameters:
      - description: Company ID
        in: path
        name: id
        required: true
        type: string
      - description: Request to update company
        in: body
        name: company_request
        required: true
        schema:
          $ref: '#/definitions/github_com_HghaVlad_trainee-match_backend_company_internal_delivery_http_dto.CompanyUpdateRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responds.ErrorResponse'
      summary: Update company
      tags:
      - company
schemes:
- http
- https
swagger: "2.0"
