// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package update_candidate

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain"
	"github.com/HghaVlad/trainee-match/backend/candidate/internal/domain/events"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCandidateRepo creates a new instance of MockCandidateRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCandidateRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCandidateRepo {
	mock := &MockCandidateRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCandidateRepo is an autogenerated mock type for the CandidateRepo type
type MockCandidateRepo struct {
	mock.Mock
}

type MockCandidateRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCandidateRepo) EXPECT() *MockCandidateRepo_Expecter {
	return &MockCandidateRepo_Expecter{mock: &_m.Mock}
}

// GetByUserID provides a mock function for the type MockCandidateRepo
func (_mock *MockCandidateRepo) GetByUserID(ctx context.Context, id uuid.UUID) (domain.Candidate, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 domain.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (domain.Candidate, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) domain.Candidate); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCandidateRepo_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockCandidateRepo_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockCandidateRepo_Expecter) GetByUserID(ctx interface{}, id interface{}) *MockCandidateRepo_GetByUserID_Call {
	return &MockCandidateRepo_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, id)}
}

func (_c *MockCandidateRepo_GetByUserID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCandidateRepo_GetByUserID_Call) Return(candidate domain.Candidate, err error) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Return(candidate, err)
	return _c
}

func (_c *MockCandidateRepo_GetByUserID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (domain.Candidate, error)) *MockCandidateRepo_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockCandidateRepo
func (_mock *MockCandidateRepo) Update(ctx context.Context, candidate domain.Candidate) (domain.Candidate, error) {
	ret := _mock.Called(ctx, candidate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Candidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Candidate) (domain.Candidate, error)); ok {
		return returnFunc(ctx, candidate)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Candidate) domain.Candidate); ok {
		r0 = returnFunc(ctx, candidate)
	} else {
		r0 = ret.Get(0).(domain.Candidate)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Candidate) error); ok {
		r1 = returnFunc(ctx, candidate)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCandidateRepo_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCandidateRepo_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - candidate domain.Candidate
func (_e *MockCandidateRepo_Expecter) Update(ctx interface{}, candidate interface{}) *MockCandidateRepo_Update_Call {
	return &MockCandidateRepo_Update_Call{Call: _e.mock.On("Update", ctx, candidate)}
}

func (_c *MockCandidateRepo_Update_Call) Run(run func(ctx context.Context, candidate domain.Candidate)) *MockCandidateRepo_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Candidate
		if args[1] != nil {
			arg1 = args[1].(domain.Candidate)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCandidateRepo_Update_Call) Return(candidate1 domain.Candidate, err error) *MockCandidateRepo_Update_Call {
	_c.Call.Return(candidate1, err)
	return _c
}

func (_c *MockCandidateRepo_Update_Call) RunAndReturn(run func(ctx context.Context, candidate domain.Candidate) (domain.Candidate, error)) *MockCandidateRepo_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventWriter creates a new instance of MockEventWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventWriter {
	mock := &MockEventWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventWriter is an autogenerated mock type for the EventWriter type
type MockEventWriter struct {
	mock.Mock
}

type MockEventWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventWriter) EXPECT() *MockEventWriter_Expecter {
	return &MockEventWriter_Expecter{mock: &_m.Mock}
}

// WriteCandidateUpserted provides a mock function for the type MockEventWriter
func (_mock *MockEventWriter) WriteCandidateUpserted(ctx context.Context, ev events.CandidateUpserted) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for WriteCandidateUpserted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, events.CandidateUpserted) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventWriter_WriteCandidateUpserted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteCandidateUpserted'
type MockEventWriter_WriteCandidateUpserted_Call struct {
	*mock.Call
}

// WriteCandidateUpserted is a helper method to define mock.On call
//   - ctx context.Context
//   - ev events.CandidateUpserted
func (_e *MockEventWriter_Expecter) WriteCandidateUpserted(ctx interface{}, ev interface{}) *MockEventWriter_WriteCandidateUpserted_Call {
	return &MockEventWriter_WriteCandidateUpserted_Call{Call: _e.mock.On("WriteCandidateUpserted", ctx, ev)}
}

func (_c *MockEventWriter_WriteCandidateUpserted_Call) Run(run func(ctx context.Context, ev events.CandidateUpserted)) *MockEventWriter_WriteCandidateUpserted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 events.CandidateUpserted
		if args[1] != nil {
			arg1 = args[1].(events.CandidateUpserted)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventWriter_WriteCandidateUpserted_Call) Return(err error) *MockEventWriter_WriteCandidateUpserted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventWriter_WriteCandidateUpserted_Call) RunAndReturn(run func(ctx context.Context, ev events.CandidateUpserted) error) *MockEventWriter_WriteCandidateUpserted_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTrManager creates a new instance of MockTrManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTrManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTrManager {
	mock := &MockTrManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTrManager is an autogenerated mock type for the TrManager type
type MockTrManager struct {
	mock.Mock
}

type MockTrManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTrManager) EXPECT() *MockTrManager_Expecter {
	return &MockTrManager_Expecter{mock: &_m.Mock}
}

// Do provides a mock function for the type MockTrManager
func (_mock *MockTrManager) Do(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Do")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTrManager_Do_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Do'
type MockTrManager_Do_Call struct {
	*mock.Call
}

// Do is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockTrManager_Expecter) Do(ctx interface{}, fn interface{}) *MockTrManager_Do_Call {
	return &MockTrManager_Do_Call{Call: _e.mock.On("Do", ctx, fn)}
}

func (_c *MockTrManager_Do_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockTrManager_Do_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTrManager_Do_Call) Return(err error) *MockTrManager_Do_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTrManager_Do_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockTrManager_Do_Call {
	_c.Call.Return(run)
	return _c
}
