// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mocks/repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	application "github.com/HghaVlad/trainee-match/backend/application/internal/domain/application"
	views "github.com/HghaVlad/trainee-match/backend/application/internal/usecase/application/views"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockappRepo is a mock of appRepo interface.
type MockappRepo struct {
	ctrl     *gomock.Controller
	recorder *MockappRepoMockRecorder
	isgomock struct{}
}

// MockappRepoMockRecorder is the mock recorder for MockappRepo.
type MockappRepoMockRecorder struct {
	mock *MockappRepo
}

// NewMockappRepo creates a new mock instance.
func NewMockappRepo(ctrl *gomock.Controller) *MockappRepo {
	mock := &MockappRepo{ctrl: ctrl}
	mock.recorder = &MockappRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockappRepo) EXPECT() *MockappRepoMockRecorder {
	return m.recorder
}

// GetForUpdateByHr mocks base method.
func (m *MockappRepo) GetForUpdateByHr(ctx context.Context, appID, hrID uuid.UUID) (*application.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetForUpdateByHr", ctx, appID, hrID)
	ret0, _ := ret[0].(*application.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetForUpdateByHr indicates an expected call of GetForUpdateByHr.
func (mr *MockappRepoMockRecorder) GetForUpdateByHr(ctx, appID, hrID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetForUpdateByHr", reflect.TypeOf((*MockappRepo)(nil).GetForUpdateByHr), ctx, appID, hrID)
}

// GetHrDetailedView mocks base method.
func (m *MockappRepo) GetHrDetailedView(ctx context.Context, appID, candID uuid.UUID) (*views.HrDetailedView, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHrDetailedView", ctx, appID, candID)
	ret0, _ := ret[0].(*views.HrDetailedView)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHrDetailedView indicates an expected call of GetHrDetailedView.
func (mr *MockappRepoMockRecorder) GetHrDetailedView(ctx, appID, candID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHrDetailedView", reflect.TypeOf((*MockappRepo)(nil).GetHrDetailedView), ctx, appID, candID)
}

// UpdateStatus mocks base method.
func (m *MockappRepo) UpdateStatus(ctx context.Context, appID uuid.UUID, status application.Status, updAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, appID, status, updAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockappRepoMockRecorder) UpdateStatus(ctx, appID, status, updAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockappRepo)(nil).UpdateStatus), ctx, appID, status, updAt)
}

// MockappStatusHistoryRepo is a mock of appStatusHistoryRepo interface.
type MockappStatusHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockappStatusHistoryRepoMockRecorder
	isgomock struct{}
}

// MockappStatusHistoryRepoMockRecorder is the mock recorder for MockappStatusHistoryRepo.
type MockappStatusHistoryRepoMockRecorder struct {
	mock *MockappStatusHistoryRepo
}

// NewMockappStatusHistoryRepo creates a new mock instance.
func NewMockappStatusHistoryRepo(ctrl *gomock.Controller) *MockappStatusHistoryRepo {
	mock := &MockappStatusHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockappStatusHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockappStatusHistoryRepo) EXPECT() *MockappStatusHistoryRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockappStatusHistoryRepo) Add(ctx context.Context, change application.StatusChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, change)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockappStatusHistoryRepoMockRecorder) Add(ctx, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockappStatusHistoryRepo)(nil).Add), ctx, change)
}
