// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/HghaVlad/trainee-match/backend/auth/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthRepo creates a new instance of MockAuthRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepo {
	mock := &MockAuthRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepo is an autogenerated mock type for the AuthRepo type
type MockAuthRepo struct {
	mock.Mock
}

type MockAuthRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepo) EXPECT() *MockAuthRepo_Expecter {
	return &MockAuthRepo_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockAuthRepo
func (_mock *MockAuthRepo) CreateUser(ctx context.Context, user domain.User, password string) (string, error) {
	ret := _mock.Called(ctx, user, password)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User, string) (string, error)); ok {
		return returnFunc(ctx, user, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User, string) string); ok {
		r0 = returnFunc(ctx, user, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User, string) error); ok {
		r1 = returnFunc(ctx, user, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepo_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockAuthRepo_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
//   - password string
func (_e *MockAuthRepo_Expecter) CreateUser(ctx interface{}, user interface{}, password interface{}) *MockAuthRepo_CreateUser_Call {
	return &MockAuthRepo_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, user, password)}
}

func (_c *MockAuthRepo_CreateUser_Call) Run(run func(ctx context.Context, user domain.User, password string)) *MockAuthRepo_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAuthRepo_CreateUser_Call) Return(s string, err error) *MockAuthRepo_CreateUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockAuthRepo_CreateUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User, password string) (string, error)) *MockAuthRepo_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOutboxWriter creates a new instance of MockOutboxWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxWriter {
	mock := &MockOutboxWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutboxWriter is an autogenerated mock type for the OutboxWriter type
type MockOutboxWriter struct {
	mock.Mock
}

type MockOutboxWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxWriter) EXPECT() *MockOutboxWriter_Expecter {
	return &MockOutboxWriter_Expecter{mock: &_m.Mock}
}

// WriteUserCreated provides a mock function for the type MockOutboxWriter
func (_mock *MockOutboxWriter) WriteUserCreated(ctx context.Context, ev domain.UserCreatedEvent) error {
	ret := _mock.Called(ctx, ev)

	if len(ret) == 0 {
		panic("no return value specified for WriteUserCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.UserCreatedEvent) error); ok {
		r0 = returnFunc(ctx, ev)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutboxWriter_WriteUserCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteUserCreated'
type MockOutboxWriter_WriteUserCreated_Call struct {
	*mock.Call
}

// WriteUserCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - ev domain.UserCreatedEvent
func (_e *MockOutboxWriter_Expecter) WriteUserCreated(ctx interface{}, ev interface{}) *MockOutboxWriter_WriteUserCreated_Call {
	return &MockOutboxWriter_WriteUserCreated_Call{Call: _e.mock.On("WriteUserCreated", ctx, ev)}
}

func (_c *MockOutboxWriter_WriteUserCreated_Call) Run(run func(ctx context.Context, ev domain.UserCreatedEvent)) *MockOutboxWriter_WriteUserCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.UserCreatedEvent
		if args[1] != nil {
			arg1 = args[1].(domain.UserCreatedEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxWriter_WriteUserCreated_Call) Return(err error) *MockOutboxWriter_WriteUserCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutboxWriter_WriteUserCreated_Call) RunAndReturn(run func(ctx context.Context, ev domain.UserCreatedEvent) error) *MockOutboxWriter_WriteUserCreated_Call {
	_c.Call.Return(run)
	return _c
}
