// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// ResumeRepo is an autogenerated mock type for the ResumeRepo type
type ResumeRepo struct {
	mock.Mock
}

// Remove provides a mock function with given fields: ctx, resumeId, candidateId
func (_m *ResumeRepo) Remove(ctx context.Context, resumeId uuid.UUID, candidateId uuid.UUID) error {
	ret := _m.Called(ctx, resumeId, candidateId)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, resumeId, candidateId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewResumeRepo creates a new instance of ResumeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewResumeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *ResumeRepo {
	mock := &ResumeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
