// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	vacancy "github.com/HghaVlad/trainee-match/backend/company/internal/domain/vacancy"
	views "github.com/HghaVlad/trainee-match/backend/company/internal/usecase/vacancy/views"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockVacancyRepo is a mock of VacancyRepo interface.
type MockVacancyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVacancyRepoMockRecorder
}

// MockVacancyRepoMockRecorder is the mock recorder for MockVacancyRepo.
type MockVacancyRepoMockRecorder struct {
	mock *MockVacancyRepo
}

// NewMockVacancyRepo creates a new mock instance.
func NewMockVacancyRepo(ctrl *gomock.Controller) *MockVacancyRepo {
	mock := &MockVacancyRepo{ctrl: ctrl}
	mock.recorder = &MockVacancyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVacancyRepo) EXPECT() *MockVacancyRepoMockRecorder {
	return m.recorder
}

// ArchiveAndGetOldStatus mocks base method.
func (m *MockVacancyRepo) ArchiveAndGetOldStatus(ctx context.Context, vacID, compID uuid.UUID) (vacancy.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveAndGetOldStatus", ctx, vacID, compID)
	ret0, _ := ret[0].(vacancy.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveAndGetOldStatus indicates an expected call of ArchiveAndGetOldStatus.
func (mr *MockVacancyRepoMockRecorder) ArchiveAndGetOldStatus(ctx, vacID, compID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveAndGetOldStatus", reflect.TypeOf((*MockVacancyRepo)(nil).ArchiveAndGetOldStatus), ctx, vacID, compID)
}

// GetSearchView mocks base method.
func (m *MockVacancyRepo) GetSearchView(ctx context.Context, vacID uuid.UUID) (*views.VacancySearch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSearchView", ctx, vacID)
	ret0, _ := ret[0].(*views.VacancySearch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSearchView indicates an expected call of GetSearchView.
func (mr *MockVacancyRepoMockRecorder) GetSearchView(ctx, vacID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSearchView", reflect.TypeOf((*MockVacancyRepo)(nil).GetSearchView), ctx, vacID)
}

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// DecrementOpenVacancies mocks base method.
func (m *MockCompanyRepo) DecrementOpenVacancies(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementOpenVacancies", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementOpenVacancies indicates an expected call of DecrementOpenVacancies.
func (mr *MockCompanyRepoMockRecorder) DecrementOpenVacancies(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementOpenVacancies", reflect.TypeOf((*MockCompanyRepo)(nil).DecrementOpenVacancies), ctx, id)
}

// MockCompMemberRepo is a mock of CompMemberRepo interface.
type MockCompMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompMemberRepoMockRecorder
}

// MockCompMemberRepoMockRecorder is the mock recorder for MockCompMemberRepo.
type MockCompMemberRepoMockRecorder struct {
	mock *MockCompMemberRepo
}

// NewMockCompMemberRepo creates a new mock instance.
func NewMockCompMemberRepo(ctrl *gomock.Controller) *MockCompMemberRepo {
	mock := &MockCompMemberRepo{ctrl: ctrl}
	mock.recorder = &MockCompMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompMemberRepo) EXPECT() *MockCompMemberRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCompMemberRepo) Get(ctx context.Context, userID, companyID uuid.UUID) (*member.CompanyMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, companyID)
	ret0, _ := ret[0].(*member.CompanyMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompMemberRepoMockRecorder) Get(ctx, userID, companyID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompMemberRepo)(nil).Get), ctx, userID, companyID)
}

// MockCacheRepo is a mock of CacheRepo interface.
type MockCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepoMockRecorder
}

// MockCacheRepoMockRecorder is the mock recorder for MockCacheRepo.
type MockCacheRepoMockRecorder struct {
	mock *MockCacheRepo
}

// NewMockCacheRepo creates a new mock instance.
func NewMockCacheRepo(ctrl *gomock.Controller) *MockCacheRepo {
	mock := &MockCacheRepo{ctrl: ctrl}
	mock.recorder = &MockCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepo) EXPECT() *MockCacheRepoMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockCacheRepo) Del(ctx context.Context, id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", ctx, id)
}

// Del indicates an expected call of Del.
func (mr *MockCacheRepoMockRecorder) Del(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacheRepo)(nil).Del), ctx, id)
}

// MockSearchRepo is a mock of SearchRepo interface.
type MockSearchRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSearchRepoMockRecorder
}

// MockSearchRepoMockRecorder is the mock recorder for MockSearchRepo.
type MockSearchRepoMockRecorder struct {
	mock *MockSearchRepo
}

// NewMockSearchRepo creates a new mock instance.
func NewMockSearchRepo(ctrl *gomock.Controller) *MockSearchRepo {
	mock := &MockSearchRepo{ctrl: ctrl}
	mock.recorder = &MockSearchRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSearchRepo) EXPECT() *MockSearchRepoMockRecorder {
	return m.recorder
}

// Index mocks base method.
func (m *MockSearchRepo) Index(ctx context.Context, vac views.VacancySearch) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, vac)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockSearchRepoMockRecorder) Index(ctx, vac interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockSearchRepo)(nil).Index), ctx, vac)
}
