// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mocks/repo_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	vacancy "github.com/HghaVlad/trainee-match/backend/company/internal/domain/vacancy"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVacancyRepo is a mock of VacancyRepo interface.
type MockVacancyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVacancyRepoMockRecorder
	isgomock struct{}
}

// MockVacancyRepoMockRecorder is the mock recorder for MockVacancyRepo.
type MockVacancyRepoMockRecorder struct {
	mock *MockVacancyRepo
}

// NewMockVacancyRepo creates a new mock instance.
func NewMockVacancyRepo(ctrl *gomock.Controller) *MockVacancyRepo {
	mock := &MockVacancyRepo{ctrl: ctrl}
	mock.recorder = &MockVacancyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVacancyRepo) EXPECT() *MockVacancyRepoMockRecorder {
	return m.recorder
}

// ArchiveAndGetOldStatus mocks base method.
func (m *MockVacancyRepo) ArchiveAndGetOldStatus(ctx context.Context, vacID, compID uuid.UUID) (vacancy.Status, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveAndGetOldStatus", ctx, vacID, compID)
	ret0, _ := ret[0].(vacancy.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ArchiveAndGetOldStatus indicates an expected call of ArchiveAndGetOldStatus.
func (mr *MockVacancyRepoMockRecorder) ArchiveAndGetOldStatus(ctx, vacID, compID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveAndGetOldStatus", reflect.TypeOf((*MockVacancyRepo)(nil).ArchiveAndGetOldStatus), ctx, vacID, compID)
}

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
	isgomock struct{}
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// DecrementOpenVacancies mocks base method.
func (m *MockCompanyRepo) DecrementOpenVacancies(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementOpenVacancies", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementOpenVacancies indicates an expected call of DecrementOpenVacancies.
func (mr *MockCompanyRepoMockRecorder) DecrementOpenVacancies(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementOpenVacancies", reflect.TypeOf((*MockCompanyRepo)(nil).DecrementOpenVacancies), ctx, id)
}

// MockCompMemberRepo is a mock of CompMemberRepo interface.
type MockCompMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompMemberRepoMockRecorder
	isgomock struct{}
}

// MockCompMemberRepoMockRecorder is the mock recorder for MockCompMemberRepo.
type MockCompMemberRepoMockRecorder struct {
	mock *MockCompMemberRepo
}

// NewMockCompMemberRepo creates a new mock instance.
func NewMockCompMemberRepo(ctrl *gomock.Controller) *MockCompMemberRepo {
	mock := &MockCompMemberRepo{ctrl: ctrl}
	mock.recorder = &MockCompMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompMemberRepo) EXPECT() *MockCompMemberRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockCompMemberRepo) Get(ctx context.Context, userID, companyID uuid.UUID) (*member.CompanyMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, userID, companyID)
	ret0, _ := ret[0].(*member.CompanyMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCompMemberRepoMockRecorder) Get(ctx, userID, companyID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCompMemberRepo)(nil).Get), ctx, userID, companyID)
}

// MockCacheRepo is a mock of CacheRepo interface.
type MockCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCacheRepoMockRecorder
	isgomock struct{}
}

// MockCacheRepoMockRecorder is the mock recorder for MockCacheRepo.
type MockCacheRepoMockRecorder struct {
	mock *MockCacheRepo
}

// NewMockCacheRepo creates a new mock instance.
func NewMockCacheRepo(ctrl *gomock.Controller) *MockCacheRepo {
	mock := &MockCacheRepo{ctrl: ctrl}
	mock.recorder = &MockCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCacheRepo) EXPECT() *MockCacheRepoMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockCacheRepo) Del(ctx context.Context, id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", ctx, id)
}

// Del indicates an expected call of Del.
func (mr *MockCacheRepoMockRecorder) Del(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockCacheRepo)(nil).Del), ctx, id)
}
