// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	company "github.com/HghaVlad/trainee-match/backend/company/internal/domain/company"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockcompanyRepo is a mock of companyRepo interface.
type MockcompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcompanyRepoMockRecorder
}

// MockcompanyRepoMockRecorder is the mock recorder for MockcompanyRepo.
type MockcompanyRepoMockRecorder struct {
	mock *MockcompanyRepo
}

// NewMockcompanyRepo creates a new mock instance.
func NewMockcompanyRepo(ctrl *gomock.Controller) *MockcompanyRepo {
	mock := &MockcompanyRepo{ctrl: ctrl}
	mock.recorder = &MockcompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcompanyRepo) EXPECT() *MockcompanyRepoMockRecorder {
	return m.recorder
}

// UpdateModerationStatusAndGetOld mocks base method.
func (m *MockcompanyRepo) UpdateModerationStatusAndGetOld(ctx context.Context, companyID uuid.UUID, status company.ModerationStatus, when time.Time) (company.ModerationStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateModerationStatusAndGetOld", ctx, companyID, status, when)
	ret0, _ := ret[0].(company.ModerationStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateModerationStatusAndGetOld indicates an expected call of UpdateModerationStatusAndGetOld.
func (mr *MockcompanyRepoMockRecorder) UpdateModerationStatusAndGetOld(ctx, companyID, status, when interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateModerationStatusAndGetOld", reflect.TypeOf((*MockcompanyRepo)(nil).UpdateModerationStatusAndGetOld), ctx, companyID, status, when)
}

// MockoutboxWriter is a mock of outboxWriter interface.
type MockoutboxWriter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxWriterMockRecorder
}

// MockoutboxWriterMockRecorder is the mock recorder for MockoutboxWriter.
type MockoutboxWriterMockRecorder struct {
	mock *MockoutboxWriter
}

// NewMockoutboxWriter creates a new mock instance.
func NewMockoutboxWriter(ctrl *gomock.Controller) *MockoutboxWriter {
	mock := &MockoutboxWriter{ctrl: ctrl}
	mock.recorder = &MockoutboxWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxWriter) EXPECT() *MockoutboxWriterMockRecorder {
	return m.recorder
}

// WriteCompanyModerationUpdated mocks base method.
func (m *MockoutboxWriter) WriteCompanyModerationUpdated(ctx context.Context, ev company.ModerationUpdatedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCompanyModerationUpdated", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCompanyModerationUpdated indicates an expected call of WriteCompanyModerationUpdated.
func (mr *MockoutboxWriterMockRecorder) WriteCompanyModerationUpdated(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCompanyModerationUpdated", reflect.TypeOf((*MockoutboxWriter)(nil).WriteCompanyModerationUpdated), ctx, ev)
}

// MockcacheRepo is a mock of cacheRepo interface.
type MockcacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockcacheRepoMockRecorder
}

// MockcacheRepoMockRecorder is the mock recorder for MockcacheRepo.
type MockcacheRepoMockRecorder struct {
	mock *MockcacheRepo
}

// NewMockcacheRepo creates a new mock instance.
func NewMockcacheRepo(ctrl *gomock.Controller) *MockcacheRepo {
	mock := &MockcacheRepo{ctrl: ctrl}
	mock.recorder = &MockcacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcacheRepo) EXPECT() *MockcacheRepoMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockcacheRepo) Del(ctx context.Context, id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Del", ctx, id)
}

// Del indicates an expected call of Del.
func (mr *MockcacheRepoMockRecorder) Del(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockcacheRepo)(nil).Del), ctx, id)
}
