// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package deleteskill

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSkillRepo creates a new instance of MockSkillRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSkillRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSkillRepo {
	mock := &MockSkillRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSkillRepo is an autogenerated mock type for the SkillRepo type
type MockSkillRepo struct {
	mock.Mock
}

type MockSkillRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSkillRepo) EXPECT() *MockSkillRepo_Expecter {
	return &MockSkillRepo_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSkillRepo
func (_mock *MockSkillRepo) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSkillRepo_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSkillRepo_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockSkillRepo_Expecter) Delete(ctx interface{}, id interface{}) *MockSkillRepo_Delete_Call {
	return &MockSkillRepo_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockSkillRepo_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockSkillRepo_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSkillRepo_Delete_Call) Return(err error) *MockSkillRepo_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSkillRepo_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *MockSkillRepo_Delete_Call {
	_c.Call.Return(run)
	return _c
}
