// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	listsearch "github.com/HghaVlad/trainee-match/backend/company/internal/usecase/vacancy/listsearch"
	gomock "github.com/golang/mock/gomock"
)

// MockResponseCacheRepo is a mock of ResponseCacheRepo interface.
type MockResponseCacheRepo struct {
	ctrl     *gomock.Controller
	recorder *MockResponseCacheRepoMockRecorder
}

// MockResponseCacheRepoMockRecorder is the mock recorder for MockResponseCacheRepo.
type MockResponseCacheRepoMockRecorder struct {
	mock *MockResponseCacheRepo
}

// NewMockResponseCacheRepo creates a new mock instance.
func NewMockResponseCacheRepo(ctrl *gomock.Controller) *MockResponseCacheRepo {
	mock := &MockResponseCacheRepo{ctrl: ctrl}
	mock.recorder = &MockResponseCacheRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResponseCacheRepo) EXPECT() *MockResponseCacheRepoMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockResponseCacheRepo) Get(ctx context.Context, key string) *listsearch.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(*listsearch.Response)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockResponseCacheRepoMockRecorder) Get(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockResponseCacheRepo)(nil).Get), ctx, key)
}

// Put mocks base method.
func (m *MockResponseCacheRepo) Put(ctx context.Context, key string, response *listsearch.Response, exp time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Put", ctx, key, response, exp)
}

// Put indicates an expected call of Put.
func (mr *MockResponseCacheRepoMockRecorder) Put(ctx, key, response, exp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockResponseCacheRepo)(nil).Put), ctx, key, response, exp)
}
