// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	listsearch "github.com/HghaVlad/trainee-match/backend/company/internal/usecase/vacancy/listsearch"
	gomock "github.com/golang/mock/gomock"
)

// MockVacancyRepo is a mock of VacancyRepo interface.
type MockVacancyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockVacancyRepoMockRecorder
}

// MockVacancyRepoMockRecorder is the mock recorder for MockVacancyRepo.
type MockVacancyRepoMockRecorder struct {
	mock *MockVacancyRepo
}

// NewMockVacancyRepo creates a new mock instance.
func NewMockVacancyRepo(ctrl *gomock.Controller) *MockVacancyRepo {
	mock := &MockVacancyRepo{ctrl: ctrl}
	mock.recorder = &MockVacancyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVacancyRepo) EXPECT() *MockVacancyRepoMockRecorder {
	return m.recorder
}

// ListPublishedSummaries mocks base method.
func (m *MockVacancyRepo) ListPublishedSummaries(ctx context.Context, requirements *listsearch.Requirements, order listsearch.Order, cursor any, limit int) (*listsearch.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPublishedSummaries", ctx, requirements, order, cursor, limit)
	ret0, _ := ret[0].(*listsearch.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPublishedSummaries indicates an expected call of ListPublishedSummaries.
func (mr *MockVacancyRepoMockRecorder) ListPublishedSummaries(ctx, requirements, order, cursor, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPublishedSummaries", reflect.TypeOf((*MockVacancyRepo)(nil).ListPublishedSummaries), ctx, requirements, order, cursor, limit)
}
