{
  "type": "record",
  "name": "CandidateUpserted",
  "namespace": "traineematch.candidate",
  "fields": [
    {
      "name": "event_id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "candidate_id",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "full_name",
      "type": "string"
    },
    {
      "name": "email",
      "type": "string"
    },
    {
      "name": "telegram",
      "type": [
        "string",
        "null"
      ]
    },
    {
      "name": "occurred_at",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    }
  ]
}