// Code generated by MockGen. DO NOT EDIT.
// Source: port.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	company "github.com/HghaVlad/trainee-match/backend/company/internal/domain/company"
	member "github.com/HghaVlad/trainee-match/backend/company/internal/domain/member"
	gomock "github.com/golang/mock/gomock"
)

// MockCompanyRepo is a mock of CompanyRepo interface.
type MockCompanyRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyRepoMockRecorder
}

// MockCompanyRepoMockRecorder is the mock recorder for MockCompanyRepo.
type MockCompanyRepoMockRecorder struct {
	mock *MockCompanyRepo
}

// NewMockCompanyRepo creates a new mock instance.
func NewMockCompanyRepo(ctrl *gomock.Controller) *MockCompanyRepo {
	mock := &MockCompanyRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyRepo) EXPECT() *MockCompanyRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCompanyRepo) Create(ctx context.Context, company *company.Company) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, company)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCompanyRepoMockRecorder) Create(ctx, company interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompanyRepo)(nil).Create), ctx, company)
}

// MockCompanyMemberRepo is a mock of CompanyMemberRepo interface.
type MockCompanyMemberRepo struct {
	ctrl     *gomock.Controller
	recorder *MockCompanyMemberRepoMockRecorder
}

// MockCompanyMemberRepoMockRecorder is the mock recorder for MockCompanyMemberRepo.
type MockCompanyMemberRepoMockRecorder struct {
	mock *MockCompanyMemberRepo
}

// NewMockCompanyMemberRepo creates a new mock instance.
func NewMockCompanyMemberRepo(ctrl *gomock.Controller) *MockCompanyMemberRepo {
	mock := &MockCompanyMemberRepo{ctrl: ctrl}
	mock.recorder = &MockCompanyMemberRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompanyMemberRepo) EXPECT() *MockCompanyMemberRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCompanyMemberRepo) Create(ctx context.Context, member *member.CompanyMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCompanyMemberRepoMockRecorder) Create(ctx, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCompanyMemberRepo)(nil).Create), ctx, member)
}

// MockoutboxWriter is a mock of outboxWriter interface.
type MockoutboxWriter struct {
	ctrl     *gomock.Controller
	recorder *MockoutboxWriterMockRecorder
}

// MockoutboxWriterMockRecorder is the mock recorder for MockoutboxWriter.
type MockoutboxWriterMockRecorder struct {
	mock *MockoutboxWriter
}

// NewMockoutboxWriter creates a new mock instance.
func NewMockoutboxWriter(ctrl *gomock.Controller) *MockoutboxWriter {
	mock := &MockoutboxWriter{ctrl: ctrl}
	mock.recorder = &MockoutboxWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutboxWriter) EXPECT() *MockoutboxWriterMockRecorder {
	return m.recorder
}

// WriteCompanyMemberAdded mocks base method.
func (m *MockoutboxWriter) WriteCompanyMemberAdded(ctx context.Context, ev member.AddedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteCompanyMemberAdded", ctx, ev)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteCompanyMemberAdded indicates an expected call of WriteCompanyMemberAdded.
func (mr *MockoutboxWriterMockRecorder) WriteCompanyMemberAdded(ctx, ev interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteCompanyMemberAdded", reflect.TypeOf((*MockoutboxWriter)(nil).WriteCompanyMemberAdded), ctx, ev)
}
